### ISSUE TITLE
(suggestion) inclusion of MoreOverlays and LightLevelOverlays

### ISSUE THREAD

**Issue by Hypsellis** [TheCBProject/NotEnoughItems#1]
Since these mods are both old old options of NotEnoughItems, it would be nice if they were reincluded in the new NEI versions.
http://minecraft.curseforge.com/projects/more-overlays?gameCategorySlug=mc-mods&projectID=243478
http://minecraft.curseforge.com/projects/light-level-overlay-reloaded?gameCategorySlug=mc-mods&projectID=226670

**Comment by covers1624** [comment]
They already are.. They were never removed..
