### ISSUE TITLE
Mob Overlay Galacticraft Moon Issue

### ISSUE THREAD

**Issue by natedogith1** [TheCBProject/NotEnoughItems#10]
The mob overlay doesn't seem to work in Galacticraft's moon dimension.  I believe this is because the overlay is asking the biome if things can spawn, rather than asking the world. (biome.getSpawnableList vs chunkProvider.getPossibleCreatures)

**Comment by covers1624** [comment]
The chunk provider diverts to the biome for the spawn map, it should work fine in the dim so can i have a screenshot of it broken please?

**Comment by natedogith1** [comment]
As I can't really screen shot non-working stuff, let me get some code sources. (https://github.com/micdoodle8/Galacticraft/blob/5d9085a5a960e027705d3f722435fb3989c3ee04/src/main/java/micdoodle8/mods/galacticraft/core/world/gen/ChunkProviderMoon.java#L428) (https://github.com/MinecraftForge/MinecraftForge/blob/260be687239b7ba04d6be2f5b9a0ce432f923cf6/patches/minecraft/net/minecraft/world/WorldServer.java.patch#L58) (net.minecraft.world.gen.ChunkProviderOverworld.getPossibleCreatures)

**Comment by covers1624** [comment]
NEI does not use those methods.. It uses Biome.getSpawnableList, witch refers to the chunk provider for a spawn list..

**Comment by natedogith1** [comment]
This is indeed what NEI currently does.  However, that doesn't refer to the chunk provider, but refers to a list internal to the biome.  The methods I listed all show examples where the biome list and the actual list have potential to differ.

**Comment by covers1624** [comment]
The only thing synced in a chunk packet to the client is the Biome
map, TileEntity map, BlockStorage and lighting calculations, not the
chunk provider, The chunk provider on the client is ALWAYS
ChunkProviderClient, the only way to get the spawns for a location is
through the biome as it is the only thing synced from the server that
has anything to do with spawn locations. Unless you can confirm
differently then it cannot be changed, so Either Galacticraft is doing
weard things with the biome then it should work fine, feel free to
mention the galacticraft dev here if you want too. 

----- Original Message -----

**Comment by natedogith1** [comment]
Oh, I had forgotten about the client/server split. Now to go inform the galacticraft dev that they're doing weird things that cause this to not work.
