### ISSUE TITLE
crash at rendering screen

### ISSUE THREAD

**Issue by Hypsellis** [TheCBProject/NotEnoughItems#100]
I get this crash randomly while playing. https://pastebin.com/MhwTuvxt
I already reported it to Buildcraft devs, but they told me it was caused by NEI. https://github.com/BuildCraft/BuildCraft/issues/3639
I use Minecraft 1.11.2, Forge 13.20.0.2310

**Comment by afdw** [comment]
[Here](https://github.com/TheCBProject/NotEnoughItems/blob/master/src/main/java/codechicken/nei/handler/NEIClientEventHandler.java#L255) `stack` can be null, and then this null passed to `RenderTooltipEvent.PostText` event, which has `@Nonnull` near `stack` field.

**Comment by covers1624** [comment]
Ahhh, cheers for catching that. Will hopefully get something out later on fixing all the things, want to finish up some of the new fmp api first.
