### ISSUE TITLE
NEI Item search and cheating interface overridden by JEI

### ISSUE THREAD

**Issue by macks2008** [TheCBProject/NotEnoughItems#101]
![2017-06-02_11 18 01](https://cloud.githubusercontent.com/assets/7110033/26736147/de5190e0-4792-11e7-82b7-a06f34b3edc9.png)
notice that JEI's wrench still shows and there is no "item count" selector under the item search panel. furthermore, it ignores NEI's item cheating toggle and instead allows item cheating depending on JEI's config. In other words, [this truth table](https://ghostbin.com/paste/7ba4c) represents my ability to cheat items as a function of the cheat mode settings

**Comment by covers1624** [comment]
1.11 or 1.10?

**Comment by macks2008** [comment]
oh sorry, this is in 1.10. would you also like to see the log files? I'll upload them when I get a chance if so. (and because I think I can safely assume the answer is yes, I'll probably upload them anyway if I get a chance)

**Comment by macks2008** [comment]
@covers1624 please read because I found a problem that wasn't just me being an idiot (I think)

Okay I realized I was overlooking the JEI integration settings.... but when I switch to NEI Item Panel, this happens to large inventories such as that of Actually Additions chests:

![2017-06-04_21 25 46](https://cloud.githubusercontent.com/assets/7110033/26767335/fe599492-496c-11e7-9b66-9b21543efdb5.png)

While I understand wanting to make sure the search bar is shown, there should really be a way to hide it easily if I need to access my hot bar, and I prefer to stay in "GUI scale: auto"

**Comment by covers1624** [comment]
There is nothing i can do about the scale besides forcing a gui scale when an inventory is opened and im not going to do that. So what here is the actual issue, you seem to have figured everything out on your own..

**Comment by macks2008** [comment]
@covers1624 I didn't suggest nor would I expect you to force a GUI scale. What's wrong with the idea of making it possible to hide the search bar as I suggested? You can press O to hide the whole extended interface so why not a key bind (perhaps shift + O) to hide just the search bar?

**Comment by covers1624** [comment]
Closing this, You are just going to have to increase your gui scale, sorry, there is nothing i can do. As you stated just hide the entire interface i cant justify adding a keybinding for JUST the searchbox as any inventory that is big enough to conflict with those is probably conflicting with other elements on the screen and hiding the entire overlay is required at that point. Fist issue, Yeah JEI Integration is a thing, if you are set to JEI stuff nei's goes away and vice versa.

**Comment by macks2008** [comment]
okay, fair enough. I understand
