### ISSUE TITLE
[1.11.2] JEI Integration crash.

### ISSUE THREAD

**Issue by Realever** [TheCBProject/NotEnoughItems#103]
Hi
My game crash after the loading screen.Here is the crash report: https://pastebin.com/5QSRY8mP

**Comment by covers1624** [comment]
NEI needs to be updated to the new JEI api apparently.

**Comment by Renadarain** [comment]
Hello,

I think this is the same issue - is there a later version of NEI than the one I'm using?

Minecraft: 1.11.2
Forge: forge-1.11.2-13.20.0.2315
NEI: NotEnoughItems-1.11.2-2.2.0.221-universal
JEI: jei_1.11.2-4.5.0.287

Crashes on both single player and server play when clicking on the main menu.

https://pastebin.com/i0VR7zMc

Regards,
Pickety

**Comment by covers1624** [comment]
I've already fixed this issue, fixing a few more and doing some major internal changes of other things before i do a release.

**Comment by Renadarain** [comment]
Thank you. :)
