### ISSUE TITLE
1.11.2 MMB clicking to get items from side/cheat panel crashes the game

### ISSUE THREAD

**Issue by CaptPatrick01** [TheCBProject/NotEnoughItems#104]
When you click the middle mouse button on the right-side cheat panel (where all the items are). The game crashes. As selecting stacks of items for me is reflexive towards the MMB, I end up crashing every five minutes while building. 
In the old renditions of this mod, the MMB is supposed to give the player an infinite/self-replenishing stack of the selected item.

**Comment by covers1624** [comment]
First off, Crash report is needed. Secondly, creative mode is a thing, so infinate stacks have been removed, also due to complications during updating, they were the main cause of most of NEI's ASM and in order to move forward they had to be dropped.

**Comment by CaptPatrick01** [comment]
[crash-2017-06-08_09.41.51-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/1061695/crash-2017-06-08_09.41.51-client.txt)

Here's a crash report that occurs.
