### ISSUE TITLE
Server commands not working

### ISSUE THREAD

**Issue by Larry84** [TheCBProject/NotEnoughItems#106]
As the title says, server-side commands such as "/toggledownfall" or "/time set" doesn't work from Nei in none but the Overworld dimension (neither Nether). I'm using MC 1.10.2 with NEI 2.1.3.220 toghether with JEI 3.14.7.419 on the FTB Beyond pack. I really hope it was just a silly mistake I made because I can't stand always having to type in the commands from the chat.

**Comment by covers1624** [comment]
The nether and end don't have a daylight cycle or weather...

**Comment by Larry84** [comment]
But other dimensions do, like the Aroma Mining World and the Void World. I wrote about the Nether to prove it wasn't an Aroma (or other mod that adds a dimension) fault. Also, the Nether doesn't have a daylight cycle but time passes while I'm there, so with a clock or the FTBUtils GUI I can see if time is changing. If I enter the commands from chat they work just fine, but if I press the buttons on the NEI GUI, even if they are the same commands (default ones), it gives me the "Toggled downfall" or "Time set to ..." messages but nothing changes.
