### ISSUE TITLE
[1.10.2] Require Dependencies Blank

### ISSUE THREAD

**Issue by tanto259** [TheCBProject/NotEnoughItems#11]
Running the 1.10.2 version from http://chickenbones.net/Pages/links.html resulted in a page in minecraft that said "Not Enough Items is missing mods it depends on. Include the following mods or remove Not Enough Items" but there are no list of the missing mods and CodeChickenCore is installed.

**Comment by covers1624** [comment]
Install jei

**Comment by Irrealist** [comment]
In that case you should mention the new dependency in the forum post and in the message OP was talking about...
