### ISSUE TITLE
Missing Graphics or broken Texture for the Leather Armour with the Mod "LeatherWorks"

### ISSUE THREAD

**Issue by huzl85** [TheCBProject/NotEnoughItems#110]
I'm using NEI and it didn't show the Leather Armour, there is a missing or broken Texture if I use the Mod "LeatherWorks" (author cleverpanda). 

With the LeatherWorks Version "LeatherWorks1.10_1.48.0" I had broken Textures and a missing tooltip

![issue](https://user-images.githubusercontent.com/29725664/27577039-826dcc62-5b1f-11e7-8897-560d3dd7ceaf.jpg)

The log show me following

[16:42:42] [Client thread/ERROR]: Failed to get tooltip: 1xitem.chestplateCloth@0 leatherworks:leather_chestplate
java.lang.NullPointerException

I posted this to the author his answer was
Looks like NEI just can't deal with the substitution aliases. JEI can though.

Now I use the LeatherWorks Version "LeatherWorks1.10_1.49.0" now I haven't any tooltip error, but the graphics / textures are still broken. I didn't find any hint in the log, but maybe I oversee something. I'm not a programmer.

![brokentexture](https://user-images.githubusercontent.com/29725664/27577264-4e316c32-5b20-11e7-9919-63f592205a95.png)

I'm not sure if this is really related to NEI, but after cleverpanda said that it looks like NEI can't deal with substitution aliases, I thought I ask and tell you about that issue.

**Comment by covers1624** [comment]
NEI shouldn't be touching any rendering on that screen.. You are viewing it from JEI's item panel, and JEI's recipe viewer. So.. Looks like an issue with LeatherWorks's Models. But anyway, chuck us your launch logs, im sure there is something in there, also going to poke @mezz as im not really sure if this is an issue with either of our mods.

**Comment by covers1624** [comment]
Yeah, going to close this, nothing JEI or NEI do would cause this. LeatherWorks has a bug, report it to them.
