### ISSUE TITLE
1.10.2 Crash GuiHook?

### ISSUE THREAD

**Issue by EPIICTHUNDERCAT** [TheCBProject/NotEnoughItems#111]
Random in World Crash! Thanks Covers <3

https://pastebin.com/KxnNkSMe

**Comment by covers1624** [comment]
Nothing I can do, update to 1.11

**Comment by EPIICTHUNDERCAT** [comment]
how about fixing a broken released mod? xD smh ihclt

**Comment by covers1624** [comment]
Well the thing is, it would take more effort to sort through all the code and interaction there that has already been rewritten in 1.11 and is impossible to port back to 1.10, than it would be for you to just use 1.11. I Understand that this is a bug but 1.10 is not supported anymore, use 1.11.
