### ISSUE TITLE
[1.10.2] NET itempanel & NEi substets no work

### ISSUE THREAD

**Issue by flapili** [TheCBProject/NotEnoughItems#114]
hi, i use :
- NotEnoughItems-1.10.2-2.1.3.220-universal
- extrautils2-1.10.2-1.5
- jei_1.10.2-3.14.7.419
- forge 12.18.3.2316

![2017-07-13_17 32 47](https://user-images.githubusercontent.com/29481952/28174268-59886742-67f1-11e7-8cb2-9953a89de620.png)

![2017-07-13_17 34 34](https://user-images.githubusercontent.com/29481952/28174339-8ce54100-67f1-11e7-9338-e00a409ca9be.png)

log : [log.txt](https://github.com/TheCBProject/NotEnoughItems/files/1145738/log.txt) / ~~pastebim in coming ...~~ You have exceeded the maximum paste size of 512 kilobytes per paste. PRO users don't have this limit!
 
maybe conflit between Extra utility and NEI ?

EDIT :  disable  extra utility resolve the problem.. but extra utility work with JEI item panel .. so , extra utility issue or NEI issue ? 
EDIT2: downgrade to EU 1.4.4 best way for now

**Comment by covers1624** [comment]
This seems to be entirely on EU2's end, I ask for its tooltip and it gets stuck in a loop for some reason.
