### ISSUE TITLE
1.12 startup crash issue

### ISSUE THREAD

**Issue by RepoDraghon** [TheCBProject/NotEnoughItems#115]
I posted the Crash, Logs and Pic files on the [CCC page](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1279956-chickenbones-mods?comment=24398)

Essentially, if I disable JEI, I get an error saying it's needed, but if it's enabled, the game crashes. Disabling NEI fixes the crash but I cannot use it...

**Comment by covers1624** [comment]
Right, 1.12 is not ready for release.

**Comment by RepoDraghon** [comment]
I understand it's listed as "Latest" but if it's not ready for even that, then why was it posted?

**Comment by covers1624** [comment]
Because the page is auto generated and I have some changes to do before it is to be used.

**Comment by RepoDraghon** [comment]
I understand, hopefully my contributing crash log and other logs help you sort some stuff out...
