### ISSUE TITLE
NotEnoughItems Version 2.4.0.229 for 1.12

### ISSUE THREAD

**Issue by Kobra299** [TheCBProject/NotEnoughItems#117]
I have got all the bits it says I need for the mod aka JEI and the CodeChickenLibs but every time I try I get this issue
[crash-2017-08-06_02.03.58-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/1203352/crash-2017-08-06_02.03.58-client.txt)

not sure what to do now

**Comment by covers1624** [comment]
1.12 is not ready yet. I have changes locally that im waiting on feedback to see if they are all good then a release will be pushed.

**Comment by Kobra299** [comment]
could I suggest that you put that 1.12 is not supported in the readme.md at this time then when it is you can remove it

**Comment by covers1624** [comment]
Well its literelly about to be pushed, so that would be pointless :D

**Comment by Robijnvogel** [comment]
@covers1624 maybe it would benefit you to create a placeholder issue telling people that NEI for MC 1.12 is not ready for release yet?
Because apparently it hasn't been pushed yet.
