### ISSUE TITLE
Inventory not showing tooltips

### ISSUE THREAD

**Issue by CommYutzy** [TheCBProject/NotEnoughItems#12]
Whenever I add NEI the tooltips stop working in my inventory (so when you hover over items in your inventory it doesn't show the pop up telling you what they are). I checked all the configs and couldn't find any settings to change to correct the issue.

CodeChickenCore 2.1.8.79
CodeChickenLib 2.2.3.58
NEI 2.1.1.145
JEI 3.8.0.241

**Comment by covers1624** [comment]
Known issue, working on it.
