### ISSUE TITLE
[1.11.2] Game Crash - Steve's Carts

### ISSUE THREAD

**Issue by Xopharios** [TheCBProject/NotEnoughItems#128]
Game crashes when intereacting with cart assembler from steve's carts. This is an NEI issue. Can only be prevent by CTRL+O before interaction. See [Crash Report](https://pastebin.com/LEAAP6R9)

------------------------------
Minecraft v1.11.2
Forge v1.11.2-13.20.1.2476

NEI v1.11.2-2.3..227
JEI v1.11.2-4.5.1.296
CodeChickenLib v1.11.2-3.0.0.298

StevesCarts v1.11.2-2.3.0.22
RebornCore v1.11.2-2.16.0.112

**Comment by covers1624** [comment]
Steve's carts seems to be squishing nei to the side and NEI can't properly render the search box text.
