### ISSUE TITLE
not 1.8.9NEI?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [TheCBProject/NotEnoughItems#13]
not 1.8.9 mods？ @Chicken-Bones @covers1624 
!(https://cloud.githubusercontent.com/assets/20567492/17759231/24ed5c80-6528-11e6-8ddb-8dd90b2ad866.png)

I think，must have player need 1.8.9 NEI（Such as me and me friend）

**Comment by covers1624** [comment]
1.8.9 is dead.. if you are still on 1.8.9 move to 1.10, literelly almost every mod is there.
