### ISSUE TITLE
Updating Screen Events

### ISSUE THREAD

**Issue by VolTorian** [TheCBProject/NotEnoughItems#130]
I've found some issues that have been resolved with some source code. How do I get gradle or maven or ant or whatever to compile the .java files in the project to get a .class file that I can replace in the mod files? I'm having some issues with crashes on recipe lookup and I'm not sure how to use the code provided in this project. Doing "javac filename.java" in command prompt just gives a LOT of errors.

**Comment by covers1624** [comment]
`gradlew setupDecompWorkspace idea` for intellij or `gradlew setupDecompWorkspace eclipse`, Open the project in the respective IDE, make changes, then `gradlew build` compiled jars will be located in `build/lib/`. Any more instructions on top of that and it would turn in to a java tutorial.
