### ISSUE TITLE
Moving multiple stacks with SHIFT+LMB does not work anymore

### ISSUE THREAD

**Issue by whocares0101** [TheCBProject/NotEnoughItems#131]
Just put together a few mods on MC1.12.2 with NEI 2.4.0.231 for testing and one of my favorite UI features doesn't work anymore.
In MC1.10.2 with NEI 2.1.3.205 it was possible by simply picking up one stack of an item with the left mouse button and then SHIFT+LMB into the target inventory to move all stacks of the same kind from the source inventory.
This worked between player inventory, chests, crafting grid and machines, basically everywhere.

Another feature which might be useful would be to hold both SHIFT+LMB down and move the mouse over some stacks which then get moved to the other inventory, not just one as with the normal SHIFT+LMB click.
I'm not sure if I saw this in another mod somewhere but it does not work in my modded 1.10 or 1.12.

**Comment by covers1624** [comment]
Its always been Shift + double left click, not single click.
