### ISSUE TITLE
1.8

### ISSUE THREAD

**Issue by Phoenixx275** [TheCBProject/NotEnoughItems#133]
It says its for 1.8 and I go into MC and it says it does not work for 1.8  
Please Help.

**Comment by covers1624** [comment]
Wot, Specify some information. Does it crash? Is NEI not visible? Not very helpful..

**Comment by Morpheus1101** [comment]
While this is indeed broken, 1.8 is'nt supported and is considered ancient, i suggest moving to minimum 1.11.2 if not 1.12.2

**Comment by covers1624** [comment]
Indeed, I was willing to hear you out but if 1.8 is broken then 1.8 is broken, im not going to push updates for ainchent stuff.
