### ISSUE TITLE
Crash on Startup 1.11.2

### ISSUE THREAD

**Issue by mastermc123** [TheCBProject/NotEnoughItems#135]
So I go to the MC launcher I hit play it starts loading all is normal but when it should start it goes back to the launcher with this message (WARNING THIS IS LARGE)

Also here is a screen shot of my mods file

![file](https://user-images.githubusercontent.com/30153786/33591863-fb7bedf0-d955-11e7-818f-4db6456f816c.png)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 114268184 bytes (108 MB) / 388145152 bytes (370 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2386 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2386.jar) 
	UCH	forge{13.20.1.2386} [Minecraft Forge] (forge-1.11.2-13.20.1.2386.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCH	bibliocraft{2.3.1} [BiblioCraft] (BiblioCraft-Mod-1.11.2.jar) 
	UCH	buildcraftlib{7.99.8.1} [BuildCraft Lib] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftcore{7.99.8.1} [BuildCraft] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftbuilders{7.99.8.1} [BC Builders] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftenergy{7.99.8.1} [BC Energy] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftfactory{7.99.8.1} [BC Factory] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftrobotics{7.99.8.1} [BC Robotics] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftsilicon{7.99.8.1} [BC Silicon] (buildcraft-7.99.8.1.jar) 
	UCH	buildcrafttransport{7.99.8.1} [BC Transport] (buildcraft-7.99.8.1.jar) 
	UCH	buildcraftcompat{7.99.0} [BuildCraft Compat] (buildcraft-compat-7.99.0.jar) 
	UCH	codechickenlib{3.0.0.284} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCE	chickenchunks{2.3.1.68} [ChickenChunks] (ChickenChunks-1.11.2-2.3.1.68-deobf.jar) 
	UCH	cpm{1.0.2} [MrCrayfish's Painting Mod] (cpm-1.0.2-mc1.11.2.jar) 
	UCH	cvmm{1.0} [MrCrayfish's Vending Machine Mod] (cvmm-1.0-mc1.11.2.jar) 
	UCH	torohealthmod{1.11.2-8} [ToroHealth Damage Indicators] (damage-indicators-mod-by-torocraft-1.11.2.jar) 
	UCH	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.6.1.jar) 
	UCH	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UCH	jei{4.5.0.294} [Just Enough Items] (jei_1.11.2-4.5.0.294.jar) 
	UCH	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCH	lunatriuscore{1.1.2.39} [LunatriusCore] (LunatriusCore-1.11.jar) 
	UCH	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCH	cdm{0.0.2} [MrCrayfish's Device Mod] (MrCrayfishs-Device-Mod-1.11.2.jar) 
	UCH	cfm{4.1.2} [MrCrayfish's Furniture Mod] (MrCrayfishs-Furniture-Mod-1.11.2.jar) 
	UCE	nei{${mod_version}} [Not Enough Items] (Not-Enough-Items-1.11.2-Recommended (3).jar) 
	UCH	schematica{1.7.8.155} [Schematica] (Schematica-Mod-1.11.jar) 
	UCH	tconstruct{1.11.2-2.7.0.26} [Tinkers' Construct] (TConstruct-1.11.2-2.7.0.26.jar) 
	UCH	tinker_io{release 2.5.5c} [Tinker I/O] (tinker_io-1.11.2-release 2.5.5c.jar) 
	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
NEICorePlugin (Not-Enough-Items-1.11.2-Recommended (3).jar)
  codechicken.nei.asm.NEITransformer
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.2.9704 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 4200 Series    '
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- TinkerDebug (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - 1 Invalid Fingerprints!: 
		chickenchunks has an invalid fingerprint.
	chickenchunks Invalid Fingerprint Reports: - 1 Invalid Fingerprints!: 
		chickenchunks has an invalid fingerprint.
	nei Invalid Fingerprint Reports: - No invalid fingerprints.:

**Comment by covers1624** [comment]
A, where did you download your mods, chicken chunks is showing invalid fingerprints, make sure you ONLY download chicken bones mods from either http://chickenbones.net/Pages/links.html or http://minecraft.curseforge.com.  
B, there is no stack trace there, you have cherry picked your crash report and that is not welcome anywhere on earth, please upload the full report to a service like http://pastebin.com

**Comment by brandon3055** [comment]
As covers mentioned it looks like you make have downloaded your mods from one of the many sites that illegally repost often broken, mislabeled or even malware infected copies of mod jars. 
To learn more about mod reposting sites and how to avoid them visit http://stopmodreposts.org/
#stopmodreposts

**Comment by mastermc123** [comment]
While I appreciate the assistance I don't understand what you meant by
"B, there is no stack trace there, you have cherry picked your crash report and that is not welcome anywhere on earth," if you can elaborate I would appreciate that.

**Comment by mastermc123** [comment]
well, I have purged my mods folder and deleted all the jar files. I've gotten the stop mod reposts addon and I am now renewing my mods folder on CurseForge thanks for the assistance.
P.S. I am leaving this open for any replies tips or tricks you or anyone may have also download this 
https://chrome.google.com/webstore/detail/stop-mod-reposts/dmooeeefhgcabgimjgdjaldjkddeopmp?utm_source=chrome-app-launcher-info-dialog

**Comment by covers1624** [comment]
Your initial issue on second glance was the use of ChickenChunks's Deobf jar, that jar is for mod developers, your issue was likely fixed as it meant you downloaded the correct jar.
