### ISSUE TITLE
Probably somewhat simple issue with NEI menu

### ISSUE THREAD

**Issue by DarkBeliel** [TheCBProject/NotEnoughItems#136]
https://imgur.com/a/ZzDsA
This sort of explains the problem without words but for whatever reason a whole part of the menu doesn't appear when i use the mod although I do have the mod and forge registers and runs it, it doesn't seem to bring up the entire save menu nor any of the added menu's. When i go through the menu's and enable "Not Enough Items" it will only have crafting available

**Comment by DarkBeliel** [comment]
Also note that i don't have any other mods besides the ones required

**Comment by covers1624** [comment]
You need to turn on Cheat mode in the world config. Options > Top left Make sure its on world > Cycle from Recipe mode to Cheat mode.
