### ISSUE TITLE
crash when displaying JEI menu

### ISSUE THREAD

**Issue by Hypsellis** [TheCBProject/NotEnoughItems#139]
I get this crash when trying to display JEI menu, it seems something goes wrong with CodeChickenLib. https://pastebin.com/CC9eaDS7

**Comment by covers1624** [comment]
You have a mod causing JEI to not load properly, likely Primitive Mobs as i debugged this exact same crash on discord with a friend yesterday. Update ALL your mods in the pack, If that doesn't solve it, provide your full log file.

**Comment by Hypsellis** [comment]
All my mods are already updated, anyway here is the full log.
[latest.log](https://github.com/TheCBProject/NotEnoughItems/files/1630638/latest.log)

**Comment by covers1624** [comment]
Yeah appears JEI is somehow in a broken state from one of your mods, most likely PrimitveMobs (the fix was to remove it or backdate it i think), @mezz any ideas why JEI would be in an invalid state from a plugin not starting properly?

**Comment by covers1624** [comment]
Ok, can confirm it is PrimitiveMobs, they are bricking JEI with their plugin.  
![](http://ss.covers1624.net/zrjfs23.png)
