### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by EarthMonster** [TheCBProject/NotEnoughItems#141]
My **anti-virus** is blocking it for **malicious software** is this normal? It did it for **TooManyItems** from a different source as well.

**Comment by EarthMonster** [comment]
It was McAfee web adviser btw

**Comment by covers1624** [comment]
Where did you download the jar from.

**Comment by covers1624** [comment]
As long as you downloaded the jars from either www.curse.com / www.curseforge.com or CB's webiste chickenbones.net Then it is safe to ignore. If you downloaded the jar from any place other than those i highly reccomend installing this chrome / firefox plugin http://stopmodreposts.org/
