### ISSUE TITLE
Cant right click craft

### ISSUE THREAD

**Issue by niklas2233** [TheCBProject/NotEnoughItems#143]
Hey
Dont know if this is the mod that add the right click to craft a hole stack
If it is it dosnt work, atleast not on Forever stranded and Direwolf 20 1.12 they dont have nei as default but added it and the feature does not work. got wrong on left and right sorry

**Comment by covers1624** [comment]
Have you even tried Shift + leftclick? Im 99% sure its a vanilla thing now.

**Comment by niklas2233** [comment]
yeah but thats put it in your inventory. what i mean is when you right click you get the hole stack on the mouse in stead of going directly to your inventory

**Comment by covers1624** [comment]
[CraftingTweaks](https://minecraft.curseforge.com/projects/crafting-tweaks?gameCategorySlug=mc-mods&projectID=233071) has the feature you are looking for.
