### ISSUE TITLE
Missing Recipe GUI Look and feel

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/NotEnoughItems#145]
Missing NEI Look and feel and no options to look for:
ScreenShot of JEI: https://imgur.com/rEM4NaX
ScreenShot of NEI:  https://imgur.com/ze3ZTmV

**Comment by covers1624** [comment]
Correct. It will not be added back. Get used to JEI's feel. It would be an absolute nightmare to make it work properly, and JEI's is soo much cleaner and easier to use.

**Comment by jredfox** [comment]
Well you could have waited to close the issue.

I could ask for an interface to change the gui for it and or engine

**Comment by covers1624** [comment]
Thats the 'Absolute nightmare' part. Its not possible without ASM'ing up JEI and im not going to do that.

**Comment by jredfox** [comment]
No it's not that's like saying your not going to override the pannel because you would have to replace stuff for jei but, they got better and more interfacial so you should be able to overrid it I just made a request there

**Comment by jredfox** [comment]
I suggest taking a vote. I think JEI Will comply and let you override their recipe gui and pages

**Comment by covers1624** [comment]
You don't understand how the ItemPanel works then. It doesnt override JEI at all, it literelly just toggles JEI's item pannel config and displays its own. Doing the same for recipes is not something im going to do. Its still a no even if mezz adds a hook of some sort. Please just stop, im not adding it back, as i've said, JEI's is a lot easier to use and cleaner.
