### ISSUE TITLE
NEI Overlay Display Glitches

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/NotEnoughItems#146]
Version NotEnoughItems-1.12.2-2.4.1.233-universal

Potion issues:
Image of Current: https://imgur.com/dlnF8vr
Image of Past: https://imgur.com/YX69H3L

Other glitches
![2018-02-24_06 18 28](https://user-images.githubusercontent.com/9736369/36630614-efa5034a-192e-11e8-9726-ced78df27011.png)

**Comment by jredfox** [comment]
Also it says item subsets could you change it back to nei subsets message on bar?

**Comment by AlexForgotMyAccountCreatedATempOne** [comment]
I think this is related.

When ingame recipes window is closed I can place items in all inventory slots and crafting grid, see pic, the first row in inventory.
But when I open ingame recipe, inventory window gets shifted to the right and now I can't place items in slots to the right, see crafting grid and second and third row of inventory. Items just get thrown away like if I dropped them off inventory window.
![2018-04-20_18 58 56](https://user-images.githubusercontent.com/31270755/39061486-1eb71988-44cd-11e8-806a-d038179a8f4d.jpg)

Additionally see the top right, the "Next" button, when I open ingame recipes the text gets all garbled up!

(NotEnoughItems-1.12.2-2.4.1.233-universal)

**Comment by covers1624** [comment]
Unable to reproduce OP's issues. Regarding vanilla recipe book stuff. I'm afraid it would be a rewrite to the entire layout system and is something ill look in to for 1.13.

**Comment by jredfox** [comment]
the thing was it never occurred to me during recipe book It was with the left tabs and didn't fire every time go into an already existing world
