### ISSUE TITLE
[Enhancement] Request Control + a

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/NotEnoughItems#147]
in search bar want to cancel search hit control + a and then hit backspace but, although this is in jei it's not in nei search bar.

**Comment by covers1624** [comment]
This currently isn't possible with the Gui elements NEI uses and Im already planing a rewrite for 1.13, this won't be happening in 1.12.

**Comment by jredfox** [comment]
I wouldn't plan on direct port to 1.13 since it has graphic issues they still haven't fixed at least with windows. It's very visible once you hit f+11

**Comment by covers1624** [comment]
I'm on linux. Its a long time before 1.13 will be viable for modding with all the changes Forge is going through. Anyway, this is OTT.
