### ISSUE TITLE
Control + 0 Not Hiding JEI Pannel

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/NotEnoughItems#149]
Control + 0 Not Hiding JEI Panel however it hides NEI panel for users. Yes I checked removing nei does in fact hide jei with control + o. So could you also hide jei panel as well especially since it's default configurations.

Not sure if this is an issue so I am going to post this question here since it's related: in the older nei versions the panels would not be visible unless your in inventory this sounds like an issue or enhancement that is necessary. Not 100% going to kill people just thought you might want to know it's not in there without opening another issue

**Comment by covers1624** [comment]
Suicidal remarks or threats are not tolerated here. Please seek help.
