### ISSUE TITLE
Recipies not showing up for various mods 

### ISSUE THREAD

**Issue by Zerys2424** [TheCBProject/NotEnoughItems#15]
e.g. blood magic some do others dont. There aint any error thrown, just recipies not showing up at all when pressing R on them, others do others dont. 

Edit: ****
- Blood Magic
- IC2
- Psi
- Roots

Im sure plenty others as well

Blood Magic Version: BloodMagic-1.9.4-2.0.3-54
NEI: NotEnoughItems-1.9.4-2.0.1.133-universal
Core: CodeChickenCore-1.9.4-2.0.4.71-universal
Minecraft: 1.9.4
Forge: forge-1.9.4-12.17.0.2051

**Comment by gigabit101** [comment]
nei use's jeis recipe lookup this is nothing to do with NEI

**Comment by covers1624** [comment]
You are using 1.9.4, there are no recipe handlers for those mods in 1.9.4, mod devs are not to make handlers for NEI, USE JEI!!
