### ISSUE TITLE
[Enhancement] Hiding When Not in Right Creative Tab

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/NotEnoughItems#151]
Hide all panels except to the left once you are not in right creative tab like older nei does. It use to do this because it was understood that the user was switching to vanilla mod to look for items.

Old NEI hiding mechanics
![2018-02-25_22 52 54](https://user-images.githubusercontent.com/9736369/36653936-a0f5b16c-1a7e-11e8-8617-136181cea1c8.png)

**Comment by covers1624** [comment]
This was an intentional change, its easier the way it is now due to the JEI integration NEI has.

**Comment by jredfox** [comment]
well you want scrolling in both vanilla and jei tabs when your not in inventory? I sure don't could you disable one or the other depending on where the mouse is or something?
