### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by darthvader45** [TheCBProject/NotEnoughItems#152]
Crash when shift-clicking items while in creative.  1.10.2 version.  I can't exactly update a modpack like Sky Factory, as not all mods in it exist in 1.11.x/1.12.x afaik.

[crash-2018-03-01_21.05.24-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/1773456/crash-2018-03-01_21.05.24-client.txt)

**Comment by covers1624** [comment]
1.10 is not supported anymore. Update to 1.12.
