### ISSUE TITLE
not enough items may be causeing memory leaks 

### ISSUE THREAD

**Issue by danieljo12** [TheCBProject/NotEnoughItems#153]
so i had some problems with my modpack with 215 mods i had jei and nei and the game was stuttering every few mins. and then i reed that nei is causeing memory leaks so i deleted it and not its all fine.. please fix this "memory leak" but now i can actually play the game smoothly! without the mod.. please fix..  (so yah... im bad at explaining stuff. ok ik)

**Comment by covers1624** [comment]
Alright, As this is an extremely complex issue, please install the Sampler mod and provide the .nps dump.

**Comment by covers1624** [comment]
No information was provided, closing. If anyone has any actual profiler data for me, id be happy to take a look.
