### ISSUE TITLE
[1.11.2] Mouse wheel

### ISSUE THREAD

**Issue by TheSnowyChickens** [TheCBProject/NotEnoughItems#154]
Hello,

in the newest NEI for 1.11.2 (Date: 9.3.2018) with the modpack "Ages of Time" ,mod list and other stuff you can found here: "https://github.com/BakermanLP/ProjectRET-AoT" (We are currently in Age II), the mouse wheel options (scroll in list, item scolling, etc) dont work.

Maybe I do something wrong, but I would know what. :D 

(I deleted for myself Itemscroller mod and replace it with NEI)

**Comment by covers1624** [comment]
I can assure you they do work, perhaps you have MouseTweaks installed messing with things.
