### ISSUE TITLE
[1.10.2] Light level overlay not working?

### ISSUE THREAD

**Issue by Marcel40625** [TheCBProject/NotEnoughItems#155]
Hey there im using NEI, everything is fine except that the light levels (F7) function seems to not work.

any ideas?

Mods:
Forge.1.10.2 - 12.18.3.2511
NotEnoughItems-1.10.2-2.1.3.220-universal.jar
jei_1.10.2-3.14.7.420.jar

**Comment by covers1624** [comment]
1.10 Is not supported anymore, please update. Only thing i can think of is keybinds, make sure NEI's keybinds are setup properly.
