### ISSUE TITLE
Missing other tooltips inventory (other mods)

### ISSUE THREAD

**Issue by Lightone** [TheCBProject/NotEnoughItems#16]
Is a little issue with The Spice of Life + Appleskin (the indicator of sature and hunger dessapear) (Tooltips inventary) 

without NEI
![2016-08-23_15 51 43](https://cloud.githubusercontent.com/assets/2113099/17909493/4bccc676-694a-11e6-8314-fe3e93cf8eaf.png)

With NEI (last version of core and libs)

![2016-08-23_15 18 26](https://cloud.githubusercontent.com/assets/2113099/17909536/77ead7f2-694a-11e6-9a5f-a6a9d700d167.png)

**Comment by covers1624** [comment]
This is now fixed.
