### ISSUE TITLE
[1.12.2][2.4.1.233] Startup Crash with Astral Sorcery, Erebus and NEI

### ISSUE THREAD

**Issue by SassyCultist** [TheCBProject/NotEnoughItems#161]
This crash occured on startup and I'm not sure which mod is the exact issue. However, I think it started with the new Astral update.

https://pastebin.com/8VWwX2hf

[Erebus Issue](https://github.com/ganymedes01/TheErebus/issues/624)
[Astral Issue](https://github.com/HellFirePvP/AstralSorcery/issues/747)

Minecraft Forge: 14.23.4.2705
Astral Sorcery: 1.9.0
Erebus: 1.0.2332
NEI: 2.4.1.233

**Comment by covers1624** [comment]
I create an itemstack for an item, their event handler crashes adding a capability to the item. Im not the cause of this one.
