### ISSUE TITLE
please help, i keep getting this error while trying to open minecraft

### ISSUE THREAD

**Issue by roymustang123** [TheCBProject/NotEnoughItems#163]
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)

**Comment by covers1624** [comment]
Going to need the actual crash report to help with this.

**Comment by roymustang123** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 7/9/18 12:10 PM
Description: There was a severe problem during mod loading that has caused
the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception
from CodeChicken Lib (codechickenlib)
Caused by: java.lang.NoSuchMethodError:
net.minecraft.client.Minecraft.getMinecraft()Lnet/minecraft/client/Minecraft;
at
codechicken.lib.util.ResourceUtils.getResourceManager(ResourceUtils.java:35)
at
codechicken.lib.util.ResourceUtils.registerReloadListener(ResourceUtils.java:67)
at
codechicken.lib.render.particle.CustomParticleHandler.init(CustomParticleHandler.java:271)
at codechicken.lib.internal.proxy.ProxyClient.preInit(ProxyClient.java:54)
at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:53)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at
com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at
com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at
com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at
net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
at
net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at
com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
at
com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
at
com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
at
com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
at com.google.common.eventbus.EventBus.post(EventBus.java:217)
at
net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
at
net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:246)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
at net.minecraft.client.main.Main.main(SourceFile:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at
sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at
sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is
as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.12.2
Operating System: Windows 7 (amd64) version 6.1
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle
Corporation
Memory: 230131560 bytes (219 MB) / 671088640 bytes (640 MB) up to
1073741824 bytes (1024 MB)
JVM Flags: 8 total;
-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
-Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
-XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50
-XX:G1HeapRegionSize=16M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: MCP 9.42 Powered by Forge 14.23.4.2730 14 mods loaded, 14 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized
'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E'
= Errored

| State | ID                  | Version       | Source
              | Signature                                |
|:----- |:------------------- |:-------------
|:-----------------------------------------
|:---------------------------------------- |
| UCH   | minecraft           | 1.12.2        | minecraft.jar
               | None                                     |
| UCH   | mcp                 | 9.42          | minecraft.jar
               | None                                     |
| UCH   | FML                 | 8.0.99.99     |
forge-1.12.2-14.23.4.2730.jar             |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCH   | forge               | 14.23.4.2730  |
forge-1.12.2-14.23.4.2730.jar             |
e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCH   | betterbuilderswands | 0.11.1        |
Better-Builders-Wands-Mod-1.12.jar        | None
         |
| UCEE  | codechickenlib      | 3.2.0.345     |
CodeChickenLib-1.12.2-3.2.0.345-deobf.jar | None
         |
| UC    | chickenchunks       | 2.4.1.71      |
ChickenChunks-1.12.2-2.4.1.71-deobf.jar   | None
         |
| UC    | customspawner       | 3.11.4        |
CustomMobSpawner-3.11.4.jar               | None
         |
| UC    | mocreatures         | 12.0.4        | DrZharks MoCreatures
Mod-12.0.4.jar       | None                                     |
| UC    | enderstorage        | 2.4.4.132     |
EnderStorage-1.12.2-2.4.4.132-deobf.jar   | None
         |
| UC    | extrautils2         | 1.0           | extrautils2-1.12-1.7.6.jar
              | None                                     |
| UC    | jei                 | 4.9.1.179     | jei_1.12.2-4.9.1.179.jar
              | None                                     |
| UC    | nei                 | 2.4.1         |
NotEnoughItems-1.12.2-2.4.1.233-deobf.jar | None
         |
| UC    | projecte            | 1.12-PE1.3.1B | ProjectE-1.12-PE1.3.1B.jar
              | None                                     |

Loaded coremods (and transformers):
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13'
Renderer: 'GeForce GT 740/PCIe/SSE2'
christopher pouliot

**Comment by covers1624** [comment]
You have the deobf version of ccl installed, the one for mod developers, you want the universal version.
