### ISSUE TITLE
New issue with recently updated Direwolf20 1.12.2 pack

### ISSUE THREAD

**Issue by RepoDraghon** [TheCBProject/NotEnoughItems#165]
umm, I disabled the mod but left it in the pack (using Twitch app) and the mod pack is running fine now, but I'd like to use this mod too...

[crash-2018-07-19_21.11.15-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/2212437/crash-2018-07-19_21.11.15-client.txt)

**Comment by RepoDraghon** [comment]
also, after posting that, I was redirected to another site for shoes?! wtf? lol...

**Comment by covers1624** [comment]
You didn't need to open an issue on CB's repo, he doesn't get emails from it anymore, plus i have direct communication to him. As for me not replying in 1 day before you opened that issue, i have a life outside modding. As for your issue report. The crash report contains no stack trace, meaning i have absolutely no way of seeing whats wrong. Please upload your latest.log file.

**Comment by RepoDraghon** [comment]
[crash-2018-07-25_14.39.29-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/2229643/crash-2018-07-25_14.39.29-client.txt)
[latest.log](https://github.com/TheCBProject/NotEnoughItems/files/2229644/latest.log)
[debug.log](https://github.com/TheCBProject/NotEnoughItems/files/2229645/debug.log)

**Comment by RepoDraghon** [comment]
Sorry, I did not know bout the email thing, as for not replying, I know, I wasn't really expecting a timely reply, I know people have lives away from games, that is one of the issues for me is that I rarely have time for games these days myself... as you can see, I just now posted all that I have on the game, yes I posted aa crash report again but it's a new one, who knows, might contain something different...

**Comment by covers1624** [comment]
Please try http://chickenbones.net/maven/codechicken/NotEnoughItems/1.12.2-2.4.1.237/ and post your debug.log & crashreport (if applicable)

**Comment by RepoDraghon** [comment]
hey, that fixed it, thanks! I didn't know there was an update, the last I looked the 233 was the latest...
[debug.log](https://github.com/TheCBProject/NotEnoughItems/files/2238414/debug.log)
[latest.log](https://github.com/TheCBProject/NotEnoughItems/files/2238415/latest.log)

**Comment by covers1624** [comment]
Cool, Thanks.
