### ISSUE TITLE
problem in mods for codechicken.lib

### ISSUE THREAD

**Issue by blokhto** [TheCBProject/NotEnoughItems#166]
minecraft crashes when I open it and fails by codechicken.lib
the error appears like this 
[crash-2018-08-02_16.03.14-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/2255184/crash-2018-08-02_16.03.14-client.txt)

**Comment by covers1624** [comment]
This is NEI's issue tracker not CCL's. Anyway, this is a duplicate and you need to delete the old codechickenlib.cfg in your config folder.
