### ISSUE TITLE
Magnet and trash will not appear

### ISSUE THREAD

**Issue by CourtArtanis** [TheCBProject/NotEnoughItems#167]
Hi,
Magnet and Trash utilities will not appear, and I also cannot switch to creative+ gamemode or save inventory.
Cheat, utility and recipe modes show the same behaviour. 
I am op(4)
Both global and world settings are identical. 
Per world:
![snap 2018-08-07 at 01 03 47](https://user-images.githubusercontent.com/1242269/43746750-0c0b4d84-99de-11e8-9702-2bb04371e914.jpg)

Per world with no overrides:
![snap 2018-08-07 at 03 05 45](https://user-images.githubusercontent.com/1242269/43750135-dd11cf60-99ee-11e8-8a45-acf825392382.jpg)

Global:
![snap 2018-08-07 at 01 03 31](https://user-images.githubusercontent.com/1242269/43746767-1d0969a4-99de-11e8-929e-de1fc8300db2.jpg)

All yield same result:
![snap 2018-08-07 at 01 02 51](https://user-images.githubusercontent.com/1242269/43746777-298dd048-99de-11e8-9e15-9a712cb1baa9.jpg)

MC 1.12.2
NEI: 1.12.2-2.4.1.238
JEI: 1.12.2-4.11.0.206
Forge: 1.12.2-14.23.4.2745

All configs for NEI and JEI are default. This result is the same whatever gamemode (survival, adventure, creative) chosen.

**Comment by covers1624** [comment]
Works for me, your server (if any) is likely disabling those things. Check NEI's config on the server.
