### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by Dark-Matter-001** [TheCBProject/NotEnoughItems#17]
http://pastebin.com/UJx7XFpM

CodeChickenLib-1.10.2-2.2.3.65-universal
CodeChickenCore-1.10.2-2.1.8.79-universal
NotEnoughItems-1.10.2-2.1.1.146-universal

Have tried forge recommended 2011 and latest 2075

**Comment by covers1624** [comment]
Install jei.
