### ISSUE TITLE
Crash when closing game

### ISSUE THREAD

**Issue by Fatmice** [TheCBProject/NotEnoughItems#172]
https://github.com/mezz/JustEnoughItems/issues/1332

**Comment by covers1624** [comment]
Blame @mezz for changing things, Duplicate of https://github.com/TheCBProject/NotEnoughItems/issues/170 Ill have a fix out in a few days.

**Comment by Fatmice** [comment]
It crashes not just closing the game but also as soon as I click a button to launch multiplayer or singleplayer.  I'll rollback.
