### ISSUE TITLE
Assistance with Screen Capture?

### ISSUE THREAD

**Issue by andrewminer** [TheCBProject/NotEnoughItems#18]
I'm the author of the [Crafting Guide](http://crafting-guide.com) website, and I'm trying to make a mod to dump out all the data which I need for the site.  For a long while now, I've used NEI's item dumper to get the images I need for the site, so when I started creating my mod, I figured I'd use the code from NEI to do the same for my mod (with proper attribution, of course).

However, I'm running into a problem that while everything seems to render, items—or portions of items—with a glint effect simply don't show up in the saved image files.  Here's an example:

![screenshot-4](https://cloud.githubusercontent.com/assets/445000/18113554/b697f57a-6ee5-11e6-8a07-8d819e99bc73.png)

What I *do* notice is that when I'm in the game and run my command, the drawn items show up on the screen and look correct (i.e., all the potions are properly filled in).  So, I'm fairly convinced the problem is in [my transcription of your code](https://github.com/andrewminer/crafting-guide-exporter/blob/master/src/main/java/com/craftingguide/exporter/extensions/craftingguide/ItemIconDumperScreen.java#L149) to actually capture the screenshot itself.

Unfortunately, I'm at my wit's end as to how to solve the problem.  I've compared my code with yours line by line quite a few times, and dug around in the `RenderItem`, `Framebuffer` code, and everywhere else I can think of.  I'd be most grateful if you could take a few minutes to offer any advice on where I'm going wrong.

Thanks!

**Comment by andrewminer** [comment]
For some reason, [this change](https://github.com/andrewminer/crafting-guide-exporter/commit/b6063ef55ec679cc9788a90d6ae65e03f41ece93) seems to fix things.  I'm not sure why replacing the call to `renderItemAndEffectIntoGUI` with just `renderItemIntoGUI` should fix this problem, but my guess would be that it has something to do with which graphics buffers are used behind the scenes.  Perhaps the former draws into a buffer which isn't accessible to the screenshot code?  Anyway, if you could offer any insight, it will still be much appreciated, even though the problem itself is solved!

**Comment by covers1624** [comment]
That is interesting, So, you got it all fixed?
I do notice you are using direct GL calls, 1.8+ these all need to be converted to GlStateManager calls.

**Comment by andrewminer** [comment]
@covers1624 — Yup, all fixed!  In fact, you can see the results on http://crafting-guide.com/browse/minecraft.  All the rest of the mods covered on the site were done by hand (mostly be me).  I'm doing this to try to speed up the process of gathering all the data needed, and to be able to handle things like the latest FTB modpacks which rely extensively on MineTweaker to alter recipes.

> 1.8+ these all need to be converted to GlStateManager calls.

Yup.  I noticed that in the newer versions of the NEI code.  At the moment, I'm working on 1.7.10, so I'll switch those over for the 1.8+ version I'll ultimately want to make.

Any idea why I might have seen that bug in the first place?

**Comment by covers1624** [comment]
Cool, Not sure what may have caused it, maybe some weird issues with the FB or maybe just the order things were happening.
