### ISSUE TITLE
Items are collected after death when you have the magnet mode enabled [1.12.2]

### ISSUE THREAD

**Issue by Psy-Virus** [TheCBProject/NotEnoughItems#182]
I saw this with a backpack from the [Backpacks](https://minecraft.curseforge.com/projects/forge-backpacks) mod.
I died and collected the, through the [Gravestone - Mod](https://minecraft.curseforge.com/projects/gravestone-mod-graves) dropped, Backpack.
I saw it in my hotbar in the respawn screen.
I tried it again with disabled magnet mode and it didn't get collected.

Used Version: Not Enough Items 1.12.2-2.4.1.239

**Comment by covers1624** [comment]
Not an issue with NEI. It doesn't care if you die, it just pulls items towards your player, that means the items exist in world and can be picked up. NEI in no way adds these items to your inventory or causes them to be dropped.
