### ISSUE TITLE
Minecraft Crashing Upon Opening

### ISSUE THREAD

**Issue by ah-callie** [TheCBProject/NotEnoughItems#183]
I know that this issue is with NEI because my Minecraft will open normally when NEI is not in my mods folder.  I'm using the most recent version of NEI (.239)

https://paste.dimdev.org/adubaroyej.mccrash

**Comment by covers1624** [comment]
God damn Forge regressions.. Ill have to fix this my side..

**Comment by ah-callie** [comment]
Thanks! Hopefully it’ll be a quick fix for you.

**Comment by Acquiesence** [comment]
Is there a fix to this or not?, been trying to play on my friends modded server and I can't as I need this mod..

**Comment by InfornoFire** [comment]
It is forge being a jerk and changing how stuff can be accessed... In other words I think downgrading forge version temporarily until the problem is resolved will work

**Comment by Acquiesence** [comment]
My server is on 1.12.2 though, so if I downgrade can I still play on it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by InfornoFire** [comment]
I meant like go down acouple forge 1.12.2 versions. Although I suggest you wait for the nei update

**Comment by Acquiesence** [comment]
Oh okay will do thanks a lot ❤️

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by NonaPeach** [comment]
I just got the same error on a crash when loading the game.  Just installed Forge and the mods today.

https://paste.dimdev.org/upoqehofog.sql

**Comment by ah-callie** [comment]
I rolled Forge back to .2765 and it works fine for me for the time being.

**Comment by NonaPeach** [comment]
> I rolled Forge back to .2765 and it works fine for me for the time being.

That worked!  Thanks!

**Comment by auddie2015** [comment]
Yeah, it is definitely a forge problem. If you use Applied Energistics and/or Immersive Engineering, don't update them when you roll back Forge. Both have updated to the new Forge. They are also the only two I run that have. I don't play a modpack so it's easier for me to accommodate everyone and this is a heads up for anyone who might maintain a modpack.

**Comment by hollowearths** [comment]
I also rolled back to .2765 and NEI works again.

**Comment by covers1624** [comment]
http://chickenbones.net/maven/codechicken/NotEnoughItems/1.12.2-2.4.2.240/ Should fix the issues, I will release it once people have confirmed this.

**Comment by tehbasshunter** [comment]
@covers1624 Can confirm .240 works with recommended .2768

**Comment by covers1624** [comment]
Pushed to curse, awaiting review.
