### ISSUE TITLE
No Such Field Error Crash with NEI

### ISSUE THREAD

**Issue by Chris-The-Lion** [TheCBProject/NotEnoughItems#184]
the crash report said something about potion handlers, but the only mod explicitly stated was NEI so I'm posting this crash here, i suspect this is a new issue since google didn't come up with anything when i searched for it.

https://pastebin.com/iMxpGuEz

**Comment by covers1624** [comment]
Duplicate of: https://github.com/TheCBProject/NotEnoughItems/issues/183
