### ISSUE TITLE
FREQ: Toggle inventory profile buttons

### ISSUE THREAD

**Issue by Syndaryl** [TheCBProject/NotEnoughItems#188]
The inventory profile buttons cover the GUI in Tinkers Construct. It would be useful to be able to toggle the profile buttons visibility - I don't use them in Survival, but they're fantastic in Creative.

**Comment by covers1624** [comment]
This is a GUI scale issue, just adjust your gui scale. Not really sure on an option to hide them in 1.12. Ill be rewriting all of NEI in 1.13.
