### ISSUE TITLE
NEI crash on starting up in a mobpack 1.12.2 StoneBlock

### ISSUE THREAD

**Issue by KusanagiRyu** [TheCBProject/NotEnoughItems#189]
As stated in the title.
here's the link in Pastebin.com
https://pastebin.com/GhgWkFVD

**Comment by covers1624** [comment]
Duplicate of https://github.com/TheCBProject/NotEnoughItems/issues/183, https://github.com/TheCBProject/NotEnoughItems/issues/184, https://github.com/TheCBProject/NotEnoughItems/issues/186. Please look for closed issues first before posting.
