### ISSUE TITLE
Inventory items render issue

### ISSUE THREAD

**Issue by nikita488** [TheCBProject/NotEnoughItems#19]
![2016-09-04_17 40 38](https://cloud.githubusercontent.com/assets/6237881/18231665/1c72c484-72c8-11e6-87af-2401b2b7b822.png)

**Comment by covers1624** [comment]
This appears to be fixed, can you please verify.

**Comment by nikita488** [comment]
Yup, i think it's fixed now.
![image](https://cloud.githubusercontent.com/assets/6237881/21750132/f8f2eaea-d5bc-11e6-8c7b-1406e5c54419.png)

**Comment by covers1624** [comment]
Sweet.
