### ISSUE TITLE
Magnet mode persist on new world

### ISSUE THREAD

**Issue by tehbasshunter** [TheCBProject/NotEnoughItems#197]
Whenever you start a new world after dying/deleting one that previously had advanced options on they're not available and have to be reenabled to use.  
  
This has been the way for a good while and I think it's about time this was changed.

**Comment by covers1624** [comment]
NEI will be completely rewritten for 1.13, this will likely be changing in that rewrite. Sorry gonna close this.

**Comment by tehbasshunter** [comment]
Fair enough. Will deal with the usual work around till then.
