### ISSUE TITLE
Crashing to desktop upon opening UI ingame

### ISSUE THREAD

**Issue by DeanHippo** [TheCBProject/NotEnoughItems#203]
https://gist.github.com/DeanHippo/f412fa2117c52c294dcda05cbf4e7cc4 - crash report
Happening at random to different players across the server, sometime they can play for 2 minutes or 2 hours, it will either crash at some point during a play session or it crash when they next log in and try opening any UI functions (chest opening, crafting interface) If the player doesn't open their UI they can mine and build with blocks on their hotbar
Happens with both the last (R)elease version of NEI for 1.10.2 and the recent (B)eta release
this error report is from the latest (B)eta release.

**Comment by covers1624** [comment]
1.10.2 has not been supported for a few years at this point. Please update.
