### ISSUE TITLE
[1.7.10] Item Subset isn't showing sub menus

### ISSUE THREAD

**Issue by Preta-Crowz** [TheCBProject/NotEnoughItems#205]
![Ingame Image](https://user-images.githubusercontent.com/16697820/52179536-3af8ec80-281f-11e9-85e0-fcb0121195e3.png)
(Cursor is on [Blocks] Btn)
Item Subset isn't showing sub menus and only works on top btns
NEI Version is 1.0.5.120 and I'm using custom modpack(Hopeless) include around 250 mods.

**Comment by covers1624** [comment]
1.7.10 has not been supported for 5 years. update.
