### ISSUE TITLE
Crash mid-game

### ISSUE THREAD

**Issue by TheQKnight** [TheCBProject/NotEnoughItems#216]
Like the title says. Mid-game this crash will happen. The game just freezes and says not responding. I'm not sure if the crash is due to Midnight or NEI, so I will need a bit of help determining that. Here is the log https://pastebin.com/9JxkFssv .

If anyone can figure out whats happening, It would be greatly appreciated. Thanks

**Comment by gigabit101** [comment]
Not an NEI crash
