### ISSUE TITLE
Buttons not there

### ISSUE THREAD

**Issue by AspectSk** [TheCBProject/NotEnoughItems#223]
I was just playing when something weird happened causing me to have to restart the computer(minecraft was still open during that) its not relevant why but yeah. When i loaded the world up after the restart the buttons just dissapeared and i tried like literally everything, i pressed O, made sure the settings werent overriden(the world,global things) and even updated the mod, nothing, then i removed it, opened, then closed and added it again(deleting the config in the time to make sure the problem wasnt there, so it would generate a new one) nothing, i went into the config and the cheatmode was set to 2, hidden is false, lockmode -1, widgets enabled, all good things that should have been like that, like literally nothing worked, and the weirdest is that in my other world it worked all fine and had the exact JEI and NEI settings as the first one, i have no idea why this is not working, if you have any idea please let me know

**Comment by AspectSk** [comment]
Well i played for a bit and when(i dont think its related but) i beat the ender dragon and later i noticed it was just working again when i was in the end, however when i went back it dissapeared again

**Comment by covers1624** [comment]
Literelly no idea, someone is breaking things or you dont have them enabled. Either way nei is getting nuked in 1.14 and thats where my focuss is.
