### ISSUE TITLE
very new to mods, need help

### ISSUE THREAD

**Issue by PlatinumBeast** [TheCBProject/NotEnoughItems#224]
![Screenshot (4515)](https://user-images.githubusercontent.com/56242406/66282698-cd4d0680-e86c-11e9-9521-de022041996f.png)
im very new to mods, and idk if this is the right place, but its the only one i could find. can someone tell me what im missing and where to download it?

**Comment by covers1624** [comment]
It tells you exactly what you are missing, and you downloaf them from CurseForge.
