### ISSUE TITLE
help 1.12.2 Crash

### ISSUE THREAD

**Issue by MonsterusFly** [TheCBProject/NotEnoughItems#232]
okay so i have tryed so much to get it to work and it just crashes no matter what i dosent work 

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.9-1.12.2.jar)
  wings (wings-1.1.0-1.12.2.jar)
  ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/25/20 1:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (codechickenlib)
Caused by: codechicken.lib.configuration.ConfigFile$ConfigException: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:61)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:43)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:29)
	at codechicken.lib.configuration.ConfigFile.<init>(ConfigFile.java:19)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: codechicken.lib.configuration.ConfigParseException: Invalid value type d, @Line:20, dump_asm=true
	at codechicken.lib.configuration.ConfigTag.parseTag(ConfigTag.java:92)
	at codechicken.lib.configuration.ConfigFile.load(ConfigFile.java:59)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 984131960 bytes (938 MB) / 1946157056 bytes (1856 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2807 54 mods loaded, 53 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                    | Version           | Source                                           | Signature                                |
	|:----- |:--------------------- |:----------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft             | 1.12.2            | minecraft.jar                                    | None                                     |
	| LCH   | mcp                   | 9.42              | minecraft.jar                                    | None                                     |
	| LCH   | FML                   | 8.0.99.99         | forge-1.12.2-14.23.5.2807.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                 | 14.23.5.2807      | forge-1.12.2-14.23.5.2807.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | openmodscore          | 0.12.1            | minecraft.jar                                    | None                                     |
	| LCH   | obfuscate             | 0.2.6             | minecraft.jar                                    | None                                     |
	| LCH   | appliedenergistics2   | rv6-stable-6      | appliedenergistics2-rv6-stable-6.jar             | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | baubles               | 1.5.2             | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | bibliocraft           | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                | None                                     |
	| LCH   | bonsaitrees           | 1.1.2             | bonsaitrees-1.1.2-b144.jar                       | None                                     |
	| LCH   | cdm                   | 0.4.1             | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
	| LCH   | cfm                   | 6.2.0             | cfm-6.2.0-mc1.12.2.jar                           | None                                     |
	| LCE   | codechickenlib        | 3.2.3.357         | CodeChickenLib-1.12.2-3.2.3.357-universal(1).jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | chickenchunks         | 2.4.1.73          | ChickenChunks-1.12.2-2.4.1.73-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux          | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore              | 4.6.1             | CoFHCore-1.12.2-4.6.1.22-universal.jar           | None                                     |
	| LC    | cofhworld             | 1.3.0             | CoFHWorld-1.12.2-1.3.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | computercraft         | 1.80pr1           | ComputerCraft1.80pr1.jar                         | None                                     |
	| LC    | customspawner         | 3.11.4            | CustomMobSpawner-3.11.4.jar                      | None                                     |
	| LC    | mocreatures           | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar              | None                                     |
	| LC    | ebwizardry            | 4.1.1             | Electroblob's+Wizardry+-+4.1.1+-+MC+1.12.2.jar   | None                                     |
	| LC    | enderstorage          | 2.4.5.135         | Ender-Storage-Mod-1.12.2.jar                     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | forestry              | 5.8.2.374         | forestry_1.12.2-5.8.2.374.jar                    | None                                     |
	| LC    | forgelin              | 1.8.2             | Forgelin-1.8.2.jar                               | None                                     |
	| LC    | mantle                | 1.12-1.3.3.39     | Mantle-1.12-1.3.3.39.jar                         | None                                     |
	| LC    | tconstruct            | 1.12.2-2.11.0.106 | TConstruct-1.12.2-2.11.0.106.jar                 | None                                     |
	| LC    | exnihilocreatio       | 1.12.2-0.3.9      | exnihilocreatio-1.12.2-0.3.9.jar                 | None                                     |
	| LC    | excompressum          | 3.0.26            | ExCompressum_1.12.2-3.0.26.jar                   | None                                     |
	| LC    | extrautils2           | 1.0               | extrautils2-1.12-1.9.9.jar                       | None                                     |
	| LC    | zerocore              | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                      | None                                     |
	| LC    | bigreactors           | 1.12.2-0.4.5.65   | ExtremeReactors-1.12.2-0.4.5.65.jar              | None                                     |
	| LC    | forgemultipartcbe     | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | microblockcbe         | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar     | None                                     |
	| LC    | minecraftmultipartcbe | 2.6.1.81          | ForgeMultipart-1.12.2-2.6.1.81-universal.jar     | None                                     |
	| LC    | guideapi              | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                      | None                                     |
	| LC    | harvestcraft          | 1.12.2w           | HarvestCraft-Mod-1.12.2.jar                      | None                                     |
	| LC    | ichunutil             | 7.0.2             | iChunUtil-1.12.2-7.0.2.jar                       | None                                     |
	| LC    | hats                  | 7.0.0             | Hats-1.12.2-7.0.2.jar                            | None                                     |
	| LC    | howlingmoon           | 0.9               | Howling-Moon-Mod-1.12.2.jar                      | None                                     |
	| LC    | llibrary              | 1.7.9             | llibrary-1.7.9-1.12.2.jar                        | None                                     |
	| LC    | mekanism              | 1.12.2-9.6.7.360  | Mekanism-1.12.2-9.6.7.360.jar                    | None                                     |
	| LC    | mrtjpcore             | 2.1.3.35          | MrTJPCore-1.12.2-2.1.3.35-universal.jar          | None                                     |
	| LC    | openmods              | 0.12.1            | OpenModsLib-1.12.2-0.12.1.jar                    | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | openblocks            | 1.8               | OpenBlocks-1.12.2-1.8.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LC    | projecte              | 1.12.2-PE1.4.0    | ProjectE-1.12.2-PE1.4.0.jar                      | None                                     |
	| LC    | projectred-core       | 4.9.1.92          | ProjectRed-1.12.2-4.9.1.92-Base.jar              | None                                     |
	| LC    | thermalfoundation     | 2.6.2             | ThermalFoundation-1.12.2-2.6.2.26-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion      | 5.5.3             | ThermalExpansion-1.12.2-5.5.3.41-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermaldynamics       | 2.5.4             | ThermalDynamics-1.12.2-2.5.4.18-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | vehicle               | 0.37.0            | vehicle-0.37.0-mc1.12.2.jar                      | None                                     |
	| LC    | waystones             | 4.0.67            | Waystones_1.12.2-4.0.67.jar                      | None                                     |
	| LC    | wings                 | 1.1.0             | wings-1.1.0-1.12.2.jar                           | None                                     |
	| LC    | bauble_wings          | 1.0.0             | wings-1.1.0-1.12.2.jar                           | None                                     |
	| UD    | mobends_wings         | 1.0.0             | wings-1.1.0-1.12.2.jar                           | None                                     |

	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.9-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
wings (wings-1.1.0-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
ObfuscatePlugin (Obfuscate-Mod-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ForgelinPlugin (Forgelin-1.8.2.jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  openmods.core.OpenModsClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13476 Compatibility Profile Context 22.19.128.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
`

i am not sure what is cusing it and its starting to realy fustrate me iv tryed verius versions of forge and of codechiken lib and tryed other versions of my mods but not sure whats cousing it so any help would be much apresiated .

**Comment by covers1624** [comment]
https://github.com/TheCBProject/CodeChickenLib/issues/270
