### ISSUE TITLE
NEI buttons P, X etc Override Creative Menu Search Bar & Custom Gui  Text Field

### ISSUE THREAD

**Issue by TheCosmicNebula** [TheCBProject/NotEnoughItems#234]
When typing into the creative menu search bar, and my custom inventories text field, when typing characters that NEI uses to open certain GUI, like P for the potions GUI, and X for enchant Gui, it opens the respective GUI instead of typing into the search bar, or the text field.

1.12.2 - MC version
1.12.2-2.4.3.245 - NEI Version
1.12.2-4.15.0.291 - JEI Version

**Comment by covers1624** [comment]
1.12.2 is EOL, Sorry.
