### ISSUE TITLE
Incompatible with the latest JEI versions

### ISSUE THREAD

**Issue by iamomicron** [TheCBProject/NotEnoughItems#24]
This issue was reported to me by one of my pack beta testers. I've since replicated the issue an both logs are below:

* https://puu.sh/rqUbO/9939eaf7c8.txt
* http://pastebin.com/YwmSHXbJ

Opening the inventory screen causes the game to crash. I believe @mezz changed a few things in JEI 3.11 that might be the cause of this, specifically in [this](https://github.com/mezz/JustEnoughItems/commit/35ad02efa0a7407fe05c8c1ad3b433ad0acaa4b0) commit.

**Comment by aolko** [comment]
same here, require a fix ASAP

**Comment by gigabit101** [comment]
ItemStackElement is now IIngredientListElement that's it

**Comment by mezz** [comment]
There is also an API call to get the filtered item stacks now, `IItemListOverlay.getFilteredStacks()`.

**Comment by gigabit101** [comment]
yeah I did that already works now but covers will do it + fix some other things tomoz just done a temp patch for me atm

**Comment by covers1624** [comment]
NEI does't actually need to get the stacks but reflect the search box, to set the text and set the "hey im hidden flag".
