### ISSUE TITLE
JEI Search Bar, Subsets Menu are Invisible and other GUI's prevented from showing

### ISSUE THREAD

**Issue by iamomicron** [TheCBProject/NotEnoughItems#25]
![image](https://cloud.githubusercontent.com/assets/4225347/19134886/bb83d2ae-8b58-11e6-83dc-47a0df1b58ff.png)

Using latest JEI, CCC, CCL and NEI. Tried 'center search bar' at both true and false values with the same results.

Clicking where the search bar should be will still allow you to search as normal, but obviously this shouldn't be the case. Strangely, pressing O to turn off NEI features does not show the search bar.

Removing NEI, however, fixes the issue.

Edit: Seems like it's blocking certain other GUI's from showing on the inventory screen too. Another mod I use 'ThutCore' recently added 'Thut Wearables' to it, which opens a GUI alongside the main inventory when the button is pressed, similar to the Baubles, except the GUI is still in the main inventory rather than a new inventory. Again though, this GUI will; not show when NEI is installed, regardless of whether NEI is showing by pressing the 'O' button.

**Comment by tterrag1098** [comment]
This mod has a slew of ASM that is of dubious necessity. JEI manages to do everything NEI does, without a coremod. All this pointless ASM is not only hard to maintain, but is now causing compatibility issues too. Perhaps looking for alternate solutions is in order?

**Comment by covers1624** [comment]
The issue in question revolves arround some of my JEI integration that i seem to have derped.

**Comment by iamomicron** [comment]
As a resolution to the search box if the config option `searchBoxOwner` is set to `1` then the search box is visible. The other GUI's and subsets are unaffected.

**Comment by iamomicron** [comment]
Search bar is visible again with version `2.1.2.172`, although subsets are hidden *if* the JEI ItemPanel is used. iChisel GUI still causes a crash though.

**Comment by covers1624** [comment]
This is fixed, Subset impl with JEI search box will be coming soon, please open an issue for that so i can track it.
