### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by billybag** [TheCBProject/NotEnoughItems#26]
i have CodeChickenCore-1.10.2-2.3.2.82-universal installed as well and i also tried downloading the newest CodeCHickenLib, but it didn't help.

What other dependencies could there be? I have the newest Forge installed, too.

No error or crash log is given.

![2016-10-11 18_44_02-minecraft 1 10 2](https://cloud.githubusercontent.com/assets/8410788/19294568/ca51c23a-8fe2-11e6-9779-becfe7fe328d.png)

**Comment by kaimokene** [comment]
Do you have Just enough items installed? You need that

**Comment by covers1624** [comment]
Yes. You nerd jei.

**Comment by billybag** [comment]
Ah OK, got it. It works now, thanks.
