### ISSUE TITLE
Depends on JEI?

### ISSUE THREAD

**Issue by HeroCC** [TheCBProject/NotEnoughItems#3]
How come NotEnoughItems depends on JEI? Don't they do the same thing?

**Comment by MarkLalor** [comment]
I was wondering that too. Mostly because I thought that NotEnoughItems was an older mod.

**Comment by gigabit101** [comment]
NEI dose not show recipe any more it uses the JEI window and adds all the rest of things NEI did back like double click to search chests for that ItemStack and Creative mode+ back aswell as weather/time control there is no reason to have both and have mod authors support Both NEI and JEI

**Comment by covers1624** [comment]
As gig said.
