### ISSUE TITLE
NEI buttons overlap with FTBUtilities

### ISSUE THREAD

**Issue by Managarmr719** [TheCBProject/NotEnoughItems#31]
NEI: 1.10.2-2.1.2.156
FTBUtilities: 1.10.2-3.0.0.3

![2016-10-13_23 36 51](https://cloud.githubusercontent.com/assets/7836631/19369609/5bb9e452-919e-11e6-882b-b248f6af9ca2.png)

**Comment by gigabit101** [comment]
then disable one in the configs there is not really much that can be done with this
