### ISSUE TITLE
Code Chicken Lib Not Automatically Downloading Anymore

### ISSUE THREAD

**Issue by jredfox** [TheCBProject/NotEnoughItems#33]
Code Chicken Lib Not Automatically Downloading Anymore. It no longer generates the folder on mod launch and no longer downloads code chicken lib.  This is the latest version. I shouldn't have to manually make my own folder called 1.10.2 and then manually download code chicken lib then put it in to get this now plugin for JEI to work.

**Comment by covers1624** [comment]
Look at the curse page for CodeChickenCore.

**Comment by jredfox** [comment]
Well could you add this back?

**Comment by covers1624** [comment]
No, im moving away from coremods and the DepLoader is total cancer and is going to die. The only reason it would be needed it for NEI, i don't have any checks for CCL installed. I should do that.
