### ISSUE TITLE
NEI crash Botania

### ISSUE THREAD

**Issue by frank89722** [TheCBProject/NotEnoughItems#35]
I used the newest NEI(2.1.2.160) and Botania(r1.9-333)
When NEI install this issue can crash client
like this https://github.com/Vazkii/Botania/issues/1966

**Comment by covers1624** [comment]
Can you verify this does not happen with NEI un insalled. NEI does not touch anything that would break this.

**Comment by frank89722** [comment]
That my issue, sorry.
