### ISSUE TITLE
1.10.2 Data dumps not dumping

### ISSUE THREAD

**Issue by DadYoshi** [TheCBProject/NotEnoughItems#36]
Only a zero byte file is created with the exception of itempanel.csv.

File used is: NotEnoughItems-1.10.2-2.1.2.157-universal

**Comment by MechanosG** [comment]
I'm having problems with data dumps too.  Attempting to dump all blocks gives me a 0 byte file like DadYoshi mentioned.  Attempting to dump the item panel sometimes works, sometimes doesn't.  If I search the item panel via something like..  $ore, then try to dump it, it will dump all items and blocks in the game instead.  It seems that some things I search will properly dump, while other things, it'll just dump everything or nothing.  I can't seem to find a pattern, unless there's an item or block that's bugging out the dump code.

**Comment by covers1624** [comment]
This was fixed.
