### ISSUE TITLE
nei crash with recent release of codechickenlib/codechickencore

### ISSUE THREAD

**Issue by jdratlif** [TheCBProject/NotEnoughItems#38]
After updating CodeChickenCore / CodeChickenLib to current release version, I get a crash every time I open my inventory (pressing 'E').

Minecraft 1.10.2
Forge 2099
JEI 3.12.8.323
NEI 2.1.2.157
CodeChickenCore 2.3.5.91
CodeChickenLib 2.4.3.124

Crash logs are at http://games.technoplaza.net/temp/nei-crash.zip

Thanks. Please let me know if you need more information. Happy to help test.

**Comment by iamomicron** [comment]
Update to NEI `2.1.2.160` - I'm using latest versions and this does not occur. 

http://chickenbones.net/Pages/links.html

**Comment by jdratlif** [comment]
Using 160 I get a crash when loading any world.

New crash logs at http://games.technoplaza.net/temp/nei-crash2.zip

**Comment by covers1624** [comment]
I pushed a fixed build to curse yesterday. I have multiple telling me that all the latest versions on curse work fine.

**Comment by trabpukcip** [comment]
@covers1624 The tooltip block highlight code has not been removed cleanly, a clean install of build 160 WILL crash, with the same error that @jdratlif mentioned.

`java.lang.NumberFormatException: world.highlight_tips.value=null`

If a clean install is being done configs\NEI\client.cfg will need to be present with the following lines:
```
world
{
	highlight_tips=false
}
```

I have also made some comments on commit https://github.com/TheCBProject/NotEnoughItems/commit/6daab9dd3ab87b82488aef3376a17bab39299b37 that removed the block highlight code on how it still renders as it is not all removed, most noticeable if updating from an older version and block highlighting was enabled previously

**Comment by jdratlif** [comment]
I grabbed NEI 161 and CodeChickeLib 126. Clean config crashes with the NumberFormatException, but adding the world section with highlight_tips to the client.cfg doesn't prevent it either.

**Comment by trabpukcip** [comment]
I should clarify, I didn't just add the section to the config, I wiped the config then put just those lines in it.
