### ISSUE TITLE
Old fix for nei bug that needs merging in

### ISSUE THREAD

**Issue by modmuss50** [TheCBProject/NotEnoughItems#4]
https://github.com/modmuss50/NotEnoughFixes/blob/8fcc08253d28538cc23ca5d5bdcabfa4768ac7df/src%2Fmain%2Fjava%2Fme%2Fmodmuss50%2Fnef%2FNEFClassTransformer.java#L13

**Comment by covers1624** [comment]
My issue with this fix is that it is removing ANY null item from the ItemList ONLY when the FurnaceRecipeHandler is opened. Perhaps a sanitize function when the item list is first initialized would be better, throw some warnings and sirens in the log telling people they are doing it wrong would be a good idea too.

**Comment by modmuss50** [comment]
yeah, this was a quick fix for null items in stacks, it would need fixing when the list is made.

**Comment by covers1624** [comment]
I've checked the code for the ItemList and it is being null checked as soon as it is pulled from the item registry.. It may be a sub item that is null
