### ISSUE TITLE
Feature Request:  Enable the Sorting

### ISSUE THREAD

**Issue by IMarvinTPA** [TheCBProject/NotEnoughItems#40]
If I could figure out how to set up an NEI development environment, I might be able to handle using an API better than writing it.
In furthering my goals to accomplish: https://github.com/Inventory-Tweaks/inventory-tweaks/issues/404
but also just restoring old NEI functionality in general.
This is the second half of https://github.com/mezz/JustEnoughItems/issues/549 where after an API for sorting is added to JEI, NEI hooks into this new API to engage the sorting defined on the sorting configuration panel.

Thanks,
IMarv

**Comment by covers1624** [comment]
This is really old, if you have any intentions of continuing what you started please open another issue.

**Comment by IMarvinTPA** [comment]
Once I figured out that NEI was not responsible for sorting after 1.7, focusing efforts here became moot.
