### ISSUE TITLE
Crash when clicking "e"

### ISSUE THREAD

**Issue by grydian** [TheCBProject/NotEnoughItems#43]
http://pastebin.com/90MYTazW

**Comment by grydian** [comment]
When I remove Aroma1997Core the crash stops I figured out.  So I don't know if that helps narrow it down.

**Comment by GWSheridan** [comment]
Minecraft 1.10 crash http://pastebin.com/XbaTAHeh

that with also pressing e to view inventory closes minecraft back down to launcher 
I was using JEI but there items do not show for some reason. So added this mod seen as was compatible with JEI but nope crashes

**Comment by grydian** [comment]
Its aroma1997core.  If you want to use NEI you will need to remove that mod until the crash is fixed.

**Comment by grydian** [comment]
It appears to be uncomplication after all.  When I remove that mod everything loads.  Its replacing recipes from ic2.  Should I report this to aroma?

**Comment by covers1624** [comment]
Nah, ill poke him about it.

**Comment by covers1624** [comment]
Please verify the issue in the latest builds from CB's site.

**Comment by grydian** [comment]
Seems to be fixed and works with uncomplication and all of aroma's mods.  Thanks so much Covers you are very awesome.  I notice the TE work ;)

**Comment by covers1624** [comment]
Cheers, Check Lemmings tweets.. he tweeted a link.
