### ISSUE TITLE
[Bug] Crashes when you go into any gui on a world

### ISSUE THREAD

**Issue by BennyboyMC** [TheCBProject/NotEnoughItems#45]
If i press "e" or "escape" it will crash. I've tried on a server, and in single player, and get the crash.
[crash-2016-11-09_17.59.36-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/582136/crash-2016-11-09_17.59.36-client.txt)
I posted one earlier before i was finished with it by accident and it got closed, sorry if its seems spammy because i open a new one

**Comment by gigabit101** [comment]
is jei installed?

**Comment by BennyboyMC** [comment]
yes, i used the latest release of jei, and the recommended versions of nei, code chicken core, and code chicken lib, and those are the only mods i have running, and still get the crash

**Comment by gigabit101** [comment]
where did you get nei from curse or website?

**Comment by BennyboyMC** [comment]
the website

**Comment by gigabit101** [comment]
kk try rolling back jei to older version for now

**Comment by BennyboyMC** [comment]
ok, hopefully that will work

**Comment by covers1624** [comment]
Update JEI to 3.13.2

**Comment by BennyboyMC** [comment]
Thanks so much!
