### ISSUE TITLE
Where is the middle search bar??

### ISSUE THREAD

**Issue by Fireztonez** [TheCBProject/NotEnoughItems#47]
I know on the Older Minecraft, on other Mod Pack I can make search, with the buttom search bar and this is for me one of think I realy needed... But, on my mod-pack, I install Just Enough Items and Not Enough Items, and the search bar is not there. I look every where In the option, I make sure the Search bar is active on JEI options, noting works, the bar is not there...

After multiple attempt, whith different version of NEI and JEI, with older and newer release from Forge server and client 1.10.2, nothing work...

Finaly I remove NEI, just all the options added by NEI missing and I want to have back... Can you tell me if is normal, if is a bug or if a do something wrong??

**Comment by iamomicron** [comment]
Read #25

**Comment by covers1624** [comment]
Update to latest
