### ISSUE TITLE
Minecraft Crash on Launch, JEI/NEI Integration Error

### ISSUE THREAD

**Issue by JHolland513** [TheCBProject/NotEnoughItems#48]
Been trying to install NEI in the modpack I've been playing lately. I have all the proper file versions and dependencies loaded but it's been crashing on launch. I suspect an integration problem between nei/jei because of the NoSuchMethodError it's giving me. Full crash log attached, any help greatly appreciated.

[crash-2016-11-15_02.49.35-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/591361/crash-2016-11-15_02.49.35-client.txt)

**Comment by covers1624** [comment]
Update JEI.
