### ISSUE TITLE
Inventory search filtering causes render-glitches

### ISSUE THREAD

**Issue by Lordmau5** [TheCBProject/NotEnoughItems#49]
Minecraft version: 1.10.2
Forge version: 12.18.2.2133
JEI version: 1.10.2 - 3.13.3.377
NEI version: 1.10.2 - 2.1.2.163

![Image](https://i.lordmau5.com/1479482833-4732.png)

So the torch renders fine, since that slot isn't being affected / rendered over.
Slots that don't have a stack-size indicator also render (somewhat) fine, as seen on e.g. my TConstruct tools in the hotbar.
Though, even those seem like they are a bit too bright for the the gray overlay applied by the search filter.

**Comment by covers1624** [comment]
Please verify the issue with the latest builds from CB's site.

**Comment by covers1624** [comment]
Exists in 1.11, Though i fixed this..

**Comment by covers1624** [comment]
K, 100% fixed in 1.11 http://ss.covers1624.net/qyddh8a.png
