### ISSUE TITLE
[Forge 2043] Crash on startup

### ISSUE THREAD

**Issue by Dragonisser** [TheCBProject/NotEnoughItems#5]
Your update sadly broke it even more, latest mod version and forge 2043

http://pastebin.com/MvMZHtc4

**Comment by iamomicron** [comment]
Yup, can confirm this happens to myself too. Same crash log.

**Comment by djchena** [comment]
Same crash here.

**Comment by covers1624** [comment]
Whops my bad, fixed hopefully.

**Comment by iamomicron** [comment]
Can confirm it's fixed! Nice job!

**Comment by Dragonisser** [comment]
Now i got the same error as before. Which cc lib, core, nei and forge version are you using?

**Comment by iamomicron** [comment]
The latest downloads from the CB page and forge 2049.

ChickenChunks	2.1.3.36
CodeChickenCore	2.1.8.78
CodeChickenLib	2.2.3.57
EnderStorage	2.1.3.72
NotEnoughItems	2.1.1.145
