### ISSUE TITLE
Fix for the 1.7.10 version

### ISSUE THREAD

**Issue by crunkazcanbe** [TheCBProject/NotEnoughItems#5]
As the title says a lot of these fixes need to be in the 1.7.10 version ,and also it needs updated to the latest 1614 build of forge for 1.7.10 . Thanx man this would allow so many to update there mod packs .

**Comment by covers1624** [comment]
Ill see about a final release for 1.7.10.
The only issue is that i don't have access to the server where the update notifications come from..
