### ISSUE TITLE
Not Enough Items Not Showing ? mark button for crafting.

### ISSUE THREAD

**Issue by MCTKid** [TheCBProject/NotEnoughItems#51]
When I want to craft something, I right click the cobble stone block. But it doesn't show the ? mark box.
![2016-11-21_21 00 40](https://cloud.githubusercontent.com/assets/23649102/20511481/aec5d842-b02d-11e6-95f7-3b6886da4a12.png)
But when I hit U while hovering my cursor over my inventory cobble block, It shows the ? mark block.
![2016-11-21_21 01 05](https://cloud.githubusercontent.com/assets/23649102/20511522/e1c4d1d0-b02d-11e6-951f-2ab46c4c36cd.png)
Is this a problem or is this standard?

**Comment by gigabit101** [comment]
it tells you on the message NEI is now a JEI addon this is not a issue
