### ISSUE TITLE
Latest NEI not compatible with latest versions of CCC

### ISSUE THREAD

**Issue by iamomicron** [TheCBProject/NotEnoughItems#53]
Since the refactors made to CCC / CCL etc, the latest NEI version available on http://chickenbones.net/Pages/links.html does not work.

* [Crash log if necessary](http://pastebin.com/EfchLZiL)

The changes since this commit: https://github.com/TheCBProject/NotEnoughItems/commit/4ff5b842acf6c38a0400055104301eaf2a4dbd09 have not been added to the download page. Only version `2.1.2.164` is the available latest.

This may be intentional, in which case just feel free to tell me to mind my own business. :p

**Comment by covers1624** [comment]
Ahh, yeah nah, thats not intentional, reply to this in about 12 hours to remind me :P

**Comment by iamomicron** [comment]
Bumping to remind you. :P

**Comment by covers1624** [comment]
Cheers, Thats probably why its broken.. https://puu.sh/syua3/6d81e33791.png

**Comment by iamomicron** [comment]
Ah. Oh dear. Well, good to know I guess.. x)
