### ISSUE TITLE
[Question/Bug] How do I set NEI 1.8+ to use gamemode numbers and not names?

### ISSUE THREAD

**Issue by GazbonicAcid** [TheCBProject/NotEnoughItems#54]
How do I set NEI 1.8+ to use gamemode numbers and not names?
My server doesn't recognize gamemode names as a /gamemode arguments.
Server running spongeforge-1.10.2-2171-5.1.0-BETA-1973, but not CCC, CCL, nor NEI.
Client running
CodeChickenCore-1.10.2-2.3.5.91-universal,
CodeChickenLib-1.10.2-2.4.3.145-universal,
and NotEnoughItems-1.10.2-2.1.2.163-universal.
Also, the command custmization only allows for customizing the "/gamemode" part of the command,
the position of the arguments within this command,
but **_NOT_** any of the values used for the arguments.
Or would adding CCC, CCL, and NEI to my server fix this?
Will try adding them and seeing if that fixes this.

**Comment by majix560** [comment]
Nope, adding CCC CCL and NEI to the server made it crash.
[gameserver.log](https://github.com/TheCBProject/NotEnoughItems/files/644878/gameserver.log.txt)

**Comment by covers1624** [comment]
So, you are having issues with the gamemode button due to a retarded sponge plugin changing the syntax of the gamemode command right?
I if i understand correctly, your command wants /gamemode 1 instead of /gamemode creative right?

**Comment by majix560** [comment]
I'm a little offended you think it's a retarded thing to do to require a specific /gamemode syntax _built into vanilla_,
but yes.
Using /gamemode 0 for survival, 1 for creative, 2 for adventure, and 3 for spectator is built into the game.
Even in single player where there is no sponge,
using the game mode numbers instead of the names works.
As a matter of fact the numbers is what I tend to use when I manually type in the command anyway.

**Comment by covers1624** [comment]
I didn't mean it offend you or anything, I just don't think all that highly of sponge, I know it's needed and it's people's only choice, but I have a strong stance against removing vanilla features / changing vanilla. Anyway all that aside, the issue that needs to be fixed is Nei on the server, iirc Nei should handle the gamemode command internally on the server regardless of the command syntax. What I can also do is provide some sort of config to change the syntax to USD numbers, but that won't be till 1.11 as I have a lot of work to get through. So, can I have the full fml log from when the server crashes with Nei please?

**Comment by majix560** [comment]
sure
[Logs](https://drive.google.com/file/d/0B3j9je-_qiwhVTRVYkx3NlJNTk0/view?usp=sharing)

**Comment by covers1624** [comment]
This crash wasn't gamemode stuff, it was NEI's data on disk being corrupt somehow.. Closing as this is ancient.

**Comment by GazbonicAcid** [comment]
Crash? what the heck are you talking about?
Reopen this immediately as you've clearly got this confused with something else and didn't fully read this post.
This post is clearly nothing to do with crashes of any kind.

**Comment by covers1624** [comment]
There was an exception thrown when nei was handling an event that was the crash, the suggestion on the other hand, totallly forgot about it, Open a new issue over here: https://github.com/TheCBProject/Feedback
