### ISSUE TITLE
NEI Crash: IndexOutOfBoundsException

### ISSUE THREAD

**Issue by coder444** [TheCBProject/NotEnoughItems#57]
Hi, I crashed in my "modpack", with several mods installed, and I updated NEI today.
I opened my inventory, and noticed the search bar in front of my hotbar.
I changed NEI to not show the bar, but to use the JEI bar instead.
Then, my game crashed. I reinitialized it and it didn't crash until I opened my inventory again.

Crash Report: [http://pastebin.com/PVHU1BdW](url)

**Comment by covers1624** [comment]
Verify the issue with NEI 2.1.3.179 from http://chickenbones.net/Pages/links.html

**Comment by coder444** [comment]
covers, the issue still occurs (in 2.1.3.179). However, I have some more info for you that I forgot to provide earlier.
I opened an **inventory**(an Actually Additions Small Storage Crate), and I tried to shift-click an item into it, and then it crashed.

**Comment by mac2040** [comment]
same hear work fine until i shift click 

crash report [http://paste.ee/p/DMrt3]

**Comment by mac2040** [comment]
http://paste.ee/p/DMrt3

**Comment by covers1624** [comment]
Shift click in to any inventory or only the ActuallyAdditions one?

**Comment by coder444** [comment]
I will check in an independent collection of mods (NEI, JEI, NEI dependencies, and AA), and I will see if I can replicate the issue with only AA or Vanilla as well

**Comment by covers1624** [comment]
Roger, Testing with AA myself in dev.

**Comment by mac2040** [comment]
a minecraft chest

**Comment by coder444** [comment]
Aha. You MUST have JEI search box enabled for it to work. Still waiting on the chest though

**Comment by coder444** [comment]
Okay. Any inventory will do

**Comment by covers1624** [comment]
I can't reproduce this in dev, what mods do you have installed?

**Comment by coder444** [comment]
NEI, JEI, NEI Dependencies, and AA
With JEI search box enabled

**Comment by covers1624** [comment]
Any specific slot in the players inventory i need to be shift clicking from?

**Comment by coder444** [comment]
I don't think so...

**Comment by covers1624** [comment]
What version of JEI are you running?

**Comment by coder444** [comment]
Latest (on Curse)

**Comment by mac2040** [comment]
jei_1.10.2-3.13.6.391

**Comment by coder444** [comment]
![capture](https://cloud.githubusercontent.com/assets/14946719/21291655/ac24c32c-c49c-11e6-8ddc-a93c147483a1.PNG)

**Comment by covers1624** [comment]
Can you confirm same NEI, JEI, Actually additions versions: https://puu.sh/sTeZB/7c31afe314.png

**Comment by coder444** [comment]
Ah. CodeChickenLib is from Curse, not from the download page

**Comment by coder444** [comment]
Therefore, I have the version .178, not .180

**Comment by covers1624** [comment]
Dw, version i have wont effect this at all, just additions in other places.

**Comment by covers1624** [comment]
JEI itemPanel and JEI Search box mode right?

**Comment by coder444** [comment]
Yep

**Comment by covers1624** [comment]
Ok, can reproduce outside dev.

**Comment by covers1624** [comment]
Do you mind joining discord instead of leving 30 million git replys :P https://discord.gg/9nr3qyC

**Comment by covers1624** [comment]
Fixed in NEI 181
