### ISSUE TITLE
Overwriting Tooltip

### ISSUE THREAD

**Issue by BeardlessBrady** [TheCBProject/NotEnoughItems#59]
Hello. So when testing NEI with my mod 'Good Ol' Currency' NEI seems to overwrite some information I add to the tooltips of itemStacks well in my Block Container. Not entirely sure how to fix this, do you have any ideas, it would be much appreciated. Thanks

**Comment by covers1624** [comment]
This should be fixed as of latest commit, I want firing tooltip events, now i do.

**Comment by BeardlessBrady** [comment]
Hey this seems to be fixed on the 1.11 branch but not the 1.10. [On 1.10.2-2.1.3.219]
