### ISSUE TITLE
Rendering screen  java.lang.IllegalAccessError: tried to access field net.minecraft.client.renderer

### ISSUE THREAD

**Issue by Lightone** [TheCBProject/NotEnoughItems#6]
Happen when try open the tab Inventory (NEI Options) and try again dont happend only the first time the game crashes

forge-1.10.2-12.18.1.2046
mod list
CodeChickenCore-1.10.2-2.1.8.78-universal
jei_1.10.2-3.7.11.238
NotEnoughItems-1.10.2-2.1.1.145-universal

[Crash Log](http://pastebin.com/t4fFYnGK)

**Comment by Dragonisser** [comment]
Try 

CodeChickenLib-1.10.2-2.2.3.57-universal
CodeChickenCore-1.10.2-2.1.8.78-universal
NotEnoughItems-1.10.2-2.1.1.145-universal
jei_1.10.2-3.7.11.238

forge-1.10.2-12.18.1.2049

It seems to work for me

**Comment by covers1624** [comment]
This is an issue with the dep downloader. When CCL is auto downloaded the FIRST time the game will always crash.
