### ISSUE TITLE
Key Bindings crash

### ISSUE THREAD

**Issue by miuirussia** [TheCBProject/NotEnoughItems#63]
After eb8d103 commit, keybinding screen not working, but when world loaded this screen working normally. Maybe keybindings initialized in the wrong place?

**Comment by covers1624** [comment]
@mezz, anything pop out at you from that?

**Comment by mezz** [comment]
Yep they're right, I registered the keybindings too late so they only show up in-world. I'll PR a simple fix.

**Comment by covers1624** [comment]
Thanks, ill pull it instantly.
