### ISSUE TITLE
Not compatible with AppleSkin tooltip overlays

### ISSUE THREAD

**Issue by squeek502** [TheCBProject/NotEnoughItems#65]
From https://github.com/squeek502/AppleSkin/issues/6

> I haven't looked at the NEI code, but I would assume it's because NEI isn't providing the ItemStack when they do their tooltip rendering or has custom tooltip rendering code that bypasses the Forge event that AppleSkin relies on.

> See mezz/JustEnoughItems#388 and mezz/JustEnoughItems@311c538 for when JEI added support for the relevant Forge event.

AppleSkin [listens for `RenderTooltipEvent.PostText`](https://github.com/squeek502/AppleSkin/blob/1.10.2/java/squeek/appleskin/client/TooltipOverlayHandler.java#L37) and expects the event's `ItemStack` field to be non-null.

**Comment by covers1624** [comment]
Ahh, ill quickly add that.

**Comment by covers1624** [comment]
Now working as expected \o/ http://ss.podgeweb.com/85b8tfe.png
Commit will follow shortly.
