### ISSUE TITLE
MC Forum thread info outdated

### ISSUE THREAD

**Issue by Robijnvogel** [TheCBProject/NotEnoughItems#67]
Unlike @covers1624 said [here](https://github.com/TheCBProject/NotEnoughItems/issues/23#issuecomment-252601458), the OP of the CB mods MC Forum thread is still not updated.

Because of that, most users of the current versions CB's mods are still unaware of this place's existence.

So could you, please either
1. Get the OP of CB's original thread edited to include links to this Github (and its issue trackers) and up-to-date information on how NEI requires JEI nowadays (and why). Or
2. Get CB's original thread locked with the last post in it linking to a new thread under your direct control in which you clarify those same things.

**Comment by covers1624** [comment]
I need to talk to cb about some stuff with in the next week anyway, ill add this to my list.

**Comment by covers1624** [comment]
CB has been poked, it will be sorted.

**Comment by Robijnvogel** [comment]
I hope that the OP will be updated soon. :smile:

**Comment by Robijnvogel** [comment]
It's almost been a month and no change has been spotted.

Are you sure that it's wise decision to **not** create a new thread on the MC forums and opt for the forum admins to close the old one?

**Comment by Robijnvogel** [comment]
I thought that all mod developers were basically hermits 😕

**Comment by Robijnvogel** [comment]
300 days later and still no single change.
It might have helped hadn't you closed this issue.
