### ISSUE TITLE
java.lang.NoClassDefFoundError: codechicken/nei/config/KeyBindings

### ISSUE THREAD

**Issue by SnowShock35** [TheCBProject/NotEnoughItems#68]
Hi covers,

A quick bug report for you;

### Important Info

- Minecraft 1.10.2
- Minecraft Forge 12.18.3.2185
- CodeChicken Core 1.8+ 2.4.0.100
- NotEnoughItems 1.8+ 2.1.3.182

### Issue Description

Crash to desktop when looking up recipes for certain machines still supporting the old NEI handler causing this crash to occur (~`http://pastebin.com/jP7a9vw9`~ http://pastebin.com/sDg01AKi)

**Comment by covers1624** [comment]
That crash report is probably mouse tweaks somehow, the title of the issue isn't in that crash either..

**Comment by SnowShock35** [comment]
oh woops wrong darn pastebin

**Comment by SnowShock35** [comment]
@covers1624 there u go

**Comment by covers1624** [comment]
Ohh, tell TFox to update NEI to the latest from CB's site.

**Comment by covers1624** [comment]
infact, ill push it to curse.
