### ISSUE TITLE
Cant cheat items on a server with op

### ISSUE THREAD

**Issue by Dragonisser** [TheCBProject/NotEnoughItems#7]
As the title says. I'm op on my server and when i click the items i want to cheat nothing happens.

**Comment by Lightone** [comment]
you need activated click in config below the items and change to true (item cheating mode)

**Comment by Dragonisser** [comment]
it is activated

**Comment by covers1624** [comment]
The item pannel is controlled by JEI, do you have JEI installed on the server?

**Comment by Dragonisser** [comment]
I cant install jei on the server since it it is spigot, also it works now after restarting and using the config again.

**Comment by covers1624** [comment]
interesting, JEI handles all the item spawning so it is totally up to the config on JEI's end for that.
