### ISSUE TITLE
Item panel icon dumps not working correctly

### ISSUE THREAD

**Issue by dogboy21** [TheCBProject/NotEnoughItems#72]
Item panel icon dumps do not work the way they should, at least these bugs didn't exist in 1.7 and I don't think they're intended.

- When the max frames are set to VSync, sometimes only half of the texture gets saved

- The black background of the dump GUI gets exported with the texture

 ![Exported images](https://ss.myftb.de/J9vZOxKr.png)
Here's an example of a dump with VSync activated

Black background is a little bit annoying with transparent textures
![Glass](https://ss.myftb.de/mRkY9IjU.png)

**Comment by covers1624** [comment]
Interesting, I'll look in to it.

**Comment by covers1624** [comment]
https://github.com/TheCBProject/Feedback/issues/4
