### ISSUE TITLE
FastTransferManager crash

### ISSUE THREAD

**Issue by JetstormLP** [TheCBProject/NotEnoughItems#73]
Playing Sky Factory 3. tried to shift+Q items out of a Colossal Chest. Got the following crash to desktop.

Description: Updating screen events

java.lang.StackOverflowError: Updating screen events
	at java.util.HashMap.put(HashMap.java:611)
	at java.util.HashSet.add(HashSet.java:219)
	at codechicken.nei.FastTransferManager.findConnectedSlots(FastTransferManager.java:65)
	at codechicken.nei.FastTransferManager.findConnectedSlots(FastTransferManager.java:76)
last line repeats about 100 times. Full log attached.

[crash-2017-01-28_23.09.14-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/737336/crash-2017-01-28_23.09.14-client.txt)

**Comment by mk0003** [comment]
Same thing happened to me when i have tried get all same type items to my inventory with double click.
My log report is here: http://pastebin.com/udsYJu1J 
Also i reported to Sky Factory FTB Forums : https://forum.feed-the-beast.com/threads/collosal-chest-double-click-crash.215399/

**Comment by covers1624** [comment]
Please verify you no longer crash with this build: http://chickenbones.net/maven/codechicken/NotEnoughItems/1.10.2-2.1.3.200/
The colossal chests gui has been blacklisted from NEI's fast transfer manager.

**Comment by JetstormLP** [comment]
Can confirm no longer crashing. Doing shift+Q will only throw one item out (not a stack), can pick up a stack and double click on like item/block stacks and transfer to inventory without crashing. Thank you for a fix. Hopefully the SF3 devs will put this new version the next release.

**Comment by covers1624** [comment]
This has been fixed.
