### ISSUE TITLE
NEI Dependent on JEI . . . Jei causes crash with Slugs Class Picker otherwise I'd use it instead! 

### ISSUE THREAD

**Issue by Winddbourne** [TheCBProject/NotEnoughItems#75]
This is a rather HUGE bug. I finally tracked a conflict that was crashing my mod pack down to JEI and so I reverted to NEI because in today's modding world you really are expected to include one or the other in your pack and Slugs class picker is core to the concept. 

Unfortunately I can't find a version past 1.9 that isn't dependent on JEI. 

Why would I willingly waste system resources having both of these loaded anyway? I chose this one to AVOID the other one which is causing a crash either permanently or until a bug fix comes out from Slug. 

This one oversight makes the entire mod redundant as we can't use it as an alternative to the more popular mod. Being compatible and able to access JEI data is a good feature; being dependent on JEI means I just need to disable JEI until a fix comes out. Otherwise I'm loading a mod into memory that isn't solving my problem and also isn't really ADDING anything for my players. 

Why would anyone choose JEI when it requires another mod that does the same thing just to work?

**Comment by gigabit101** [comment]
All nei dose these days is add the save inventory slot + day/night button and creative +. It also speeds up creative tabs searching and allows the jei.

**Comment by covers1624** [comment]
Yeah, NEI is a JEI dep for several reasons. First NEI does not add recipe viewing for all mods, NEI provides an API for mods to do it themselves, as mods have moved to JEI's API it would be a constant stream of "NEI is broken there is no recipes for X mod".
