### ISSUE TITLE
[1.10.2] Client crash (JEI Int.)

### ISSUE THREAD

**Issue by DeadSix27** [TheCBProject/NotEnoughItems#77]
JEI: `jei_1.10.2-3.14.5.405.jar`
NEI: `NotEnoughItems-1.10.2-2.1.3.201-universal.jar`

Happends when I opened my inventory (creative).

If you need more information/list of mods, say so.
 
Stacktrace. https://gist.github.com/DeadSix27/b52379b2687d0aca9b8d5fcc9ea4d8e1

**Comment by SteelShot** [comment]
I am also getting this crash, fresh world as soon as the inventory is opened, chest, E keypress or any inventory - bam crash.

Crash Report: https://paste.ee/p/M6knx
Mod List: https://modlister.com/user/SteelShot

**Comment by covers1624** [comment]
@mezz did you change anything inside JEI that could cause this?

**Comment by DeadSix27** [comment]
Seems to be fixed now, using: 

JEI: `jei_1.10.2-3.14.5.406.jar`
NEI: `NotEnoughItems-1.10.2-2.1.3.201-universal.jar`

Whatever was in JEI 405 

(Probably:

> Current release 3.14.5.406
> Fix #727 Recipes issues in previous commit

)

Fixed this crash.

**Comment by SteelShot** [comment]
That did not seem to fix anything, it still says that the build version is 405 in the crash log even to i just re downloaded it
https://paste.ee/p/9RWMB

**Comment by SteelShot** [comment]
Reverted 1 version back on NEI, does seem to fix my crash issues, will investigate more

**Comment by SteelShot** [comment]
Ok, this is really weird I removed some mods, Base Matals, Modern Metals MMO Ore Spawn and WalpaperCraft and Flat colored blocks, and it seems to work fine with the latest NEI version.

I guess this can be closed
