### ISSUE TITLE
A question about permission nodes

### ISSUE THREAD

**Issue by EmanYm** [TheCBProject/NotEnoughItems#79]
Does the Forge NEI/JEI still go off the vanilla /give command and any mod that offers a /give equivalent?
([source](https://bukkit.org/threads/nei-permission-nodes.133846/))

**Comment by covers1624** [comment]
NEI if installed on a server does not use permission nodes, it uses internal packets from the client to the server to spawn the item. Ill consider this a feature request. 
https://github.com/TheCBProject/Feedback/issues/5
