### ISSUE TITLE
Crash on opening inventory

### ISSUE THREAD

**Issue by majix560** [TheCBProject/NotEnoughItems#8]
My client crashed when I pressed E to open my inventory.
Here is the console log from after the crash.
http://pastebin.com/rZNWaxex

**Comment by majix560** [comment]
May be a dupe of https://github.com/TheCBProject/NotEnoughItems/issues/7
In which case https://github.com/TheCBProject/NotEnoughItems/issues/7 was closed before the issue was fixed.

**Comment by modmuss50** [comment]
It needs updating to 1.10.2 I think

**Comment by majix560** [comment]
if that's the case, then NEI is an exception to needing updating to 1.10.2
As most 1.9.4 mods work straighting out of the box in 1.10.x, albeit sometimes with a very (very) minor issue.

**Comment by covers1624** [comment]
Nei will not load on any 1.10 version. I will support 1.10 after btm.
