### ISSUE TITLE
Crashing on opening the Inventory Screen

### ISSUE THREAD

**Issue by Gunner76th** [TheCBProject/NotEnoughItems#81]
https://github.com/mezz/JustEnoughItems/issues/759

We have NEI 2.1.3.201 and JEI 3.14.7.415 
CCC 2.4.0.101
Code Chicken Lib 2.5.6.233

**Comment by Gunner76th** [comment]
[crash-2017-03-06_22.47.06-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/823353/crash-2017-03-06_22.47.06-client.txt)

**Comment by covers1624** [comment]
https://github.com/TheCBProject/NotEnoughItems/commit/25648caa0c11752693ed5840b2ac5e1ced7379ef
