### ISSUE TITLE
[Updated][Question] Server-side config file?

### ISSUE THREAD

**Issue by EmanYm** [TheCBProject/NotEnoughItems#82]
Greetings

Isn't there supposed to be a server-side config file created to enable item spawning and other features?  All I get when I click on an item is recipes

I can't even enable creative/creative+ on my client when using it on a (hosted) server environment.

**Comment by EmanYm** [comment]
I found a separate NEI config in each of my world folders.  I'm guessing this means you can config each world separate?

I would actually prefer a global config, and an optional "PerWorld" config option in that file.
Or even a MySQL database option would be nice.

**Comment by covers1624** [comment]
This should cover it https://github.com/TheCBProject/Feedback/issues/5 Add any additional info to there.
