### ISSUE TITLE
Updating screen events

### ISSUE THREAD

**Issue by Gunner76th** [TheCBProject/NotEnoughItems#83]
Seems that build 204 has a new error in it. 
[crash-2017-03-07_20.21.25-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/826350/crash-2017-03-07_20.21.25-client.txt)
This is occurring when players open their inventory with the E key.

**Comment by Gunner76th** [comment]
Also just this report as well 
[crash-2017-03-07_20.54.08-client.txt](https://github.com/TheCBProject/NotEnoughItems/files/826388/crash-2017-03-07_20.54.08-client.txt)
That player was in creative mode when it happened if that matters.

**Comment by covers1624** [comment]
NEI's recipe stuff has been nuked as of recently.
