### ISSUE TITLE
Broken/hidden recipes that aren't actually broken nor hidden.

### ISSUE THREAD

**Issue by MechanosG** [TheCBProject/NotEnoughItems#84]
Using NEI 2.1.3.201 and JEI 3.14.7.416 on MC 1.10.2, if you enable NEIs item window/search in the JEI options, certain mods will have their recipes disappear when you try to look them up, but the recipes still technically work (and just aren't visible).  You can reproduce this by having Forge, JEI, NEI, AE2, Mekanism, and any of their requirements, then enabling NEI in JEI, and trying to look at some of AE2's or Mekanism's recipes.  They will show up as not having a recipe.  Yet if you look at possible uses for items used in those recipes, they will suddenly show up.  If you disable NEI's window and item search in JEI and use JEI to look up the recipes instead, all recipes seem to show up just fine.

**Comment by covers1624** [comment]
NEI's recipe stuff has been nuked as of recently.
