### ISSUE TITLE
ASM Transformer Crash in 1.10.2

### ISSUE THREAD

**Issue by BrisingrAerowing** [TheCBProject/NotEnoughItems#85]
Trying to use NEI with recent 1.10.2 Forge version crashes on startup with an ASM transformation error.

[Startup Log](https://gist.github.com/BrisingrAerowing/6aef37866e7af39959bc645bbaa83700)

The crash is near the end of the log.

Forge: 12.18.3.2254
Minecraft: 1.10.2
NEI: 2.1.3.204 (2.1.3.201 crashes as well)

**Comment by vinyldarkscratch** [comment]
Looking at your log files, I'm going to take a guess and say that the culprit is most likely the Backpacks! mod, based upon the fact that the following line is printed just before crashing:

`[18:20:49] [main/INFO] [STDOUT]: [brad16840.common.asm.ClassTransformer:patchGuiContainer:221]: Backpacks! has patched GuiContainer to allow its backpacks to be opened from vanilla guis`

If you were to temporarily disable that mod, does Minecraft still crash?

**Comment by BrisingrAerowing** [comment]
Still crashes without that mod.

[New Crash Report](https://gist.github.com/BrisingrAerowing/70d4dd43035e9e7249b906122172c56d)

Also, as a side note, your post took somewhere between 24-36 hours to show up for me. 😕

**Comment by covers1624** [comment]
First uninstall your Xray mod, second. Unless someone is doing ASM wrong this should never happen..

**Comment by vinyldarkscratch** [comment]
Sorry for the delay, GitHub's spam bots were inaccurately flagging my account, as such my profile was hidden from the public -- I agree with @covers1624, try disabling the XRay mod as well as possibly the ShetiPhian-ASM mod?  (Basically, we're wanting to strip down your mods list one by one, until we find the mod that's causing the game to crash.  Once we've pinpointed which one it is, we can check to see if an updated version is available for MC 1.10.2, or see if we can fix it.  ;))

**Comment by BrisingrAerowing** [comment]
Those 1.9.4 and 1.11 mods are compatible with 1.10 (usually using McJty's CompatLayer).

**Comment by BrisingrAerowing** [comment]
It's not XRay or any  of the ShetiPhian mods.

**Comment by BrisingrAerowing** [comment]
I just got rid of 20 mods I never used, and now the game starts without errors. My main guess as to which of those was the issue is Draconic Evolution, as that one has broken things before.

**Comment by BrisingrAerowing** [comment]
I just found that one of the LiteLoader mods I use (which adds horse attributes to the inventory screen) is the culprit. Wasn't expecting that.

**Comment by vinyldarkscratch** [comment]
I wasn't expecting that one either, usually LiteLoader mods don't cause compatibility issues...  But, when you mention it's purpose, that makes sense as well, glad to hear you found the problem!
