### ISSUE TITLE
Recipe menu conflicts with JEI recipe

### ISSUE THREAD

**Issue by TehBigA** [TheCBProject/NotEnoughItems#86]
If this requires JEI _(according to curseforge)_ which already has a better recipe menu why does this have one?

*On top of that:* If you open a standard `Minecraft Crafting Table` and press the `Show Recipes` sometimes the JEI menu will open and sometimes the NEI one will. If the NEI menu opens and you press escape it _*DELETES*_ anything previously put into the crafting table.

**Comment by JasonMcRay** [comment]
To little expand on this. I have noticed that if you click on the recipe in the item panel. It shows everything fine, however when you for example search uses on item in your inventory, it shows only crafting table ones.

**Comment by tfox83** [comment]
I can confirm this bug, its present in latest FTB Beyond as well.  Rolling back to 201 fixed.

**Comment by covers1624** [comment]
Fixed, and has been nuked as of recently.
