### ISSUE TITLE
NEI Subsets / Search issue

### ISSUE THREAD

**Issue by iamomicron** [TheCBProject/NotEnoughItems#9]
When _shift clicking_ a mod from the Subsets dropdown menu, the game inputs the string `@Mod.MODNAME` into the search bar.

The `Mod.` is no longer needed and as such returns 0 results for all mods, and instead should just be '@MODNAME'

Also, when viewing the Subsets, the z-index of the menu is incorrect. Items that are in your inventory appear over the subsets menu.

**Comment by covers1624** [comment]
Subsets are still broken.

**Comment by covers1624** [comment]
Shift clicking mod names is now fixed. If there is other issues please open another issue.
