### ISSUE TITLE
NEI refuses to see that I have JEI installed

### ISSUE THREAD

**Issue by NinjasInMyBasement** [TheCBProject/NotEnoughItems#91]
I would post the fml-client-latest.log However the ingame open button does not work and I cant find the file. But I have the newest version of NEI and JEI installed. ChickenLIB is working as intended. 

All the mods I have installed:
WorldEdit(Working)
NEI(partially)
ChickenLIB(Working)
JEI(Not working with NEI installed)

**Comment by covers1624** [comment]
Is this for 1.11 or 1.10?

**Comment by NinjasInMyBasement** [comment]
This was for 1.11

**Comment by covers1624** [comment]
I need a log or i can't do anything. Your launcher should have the option to open the folder your instance is located in.

**Comment by covers1624** [comment]
If you are using the new MC launcher, the fml-client-latest log wont exist and you will have to use the latest.log file

**Comment by NinjasInMyBasement** [comment]
Where can I find that file? Because I am using the New launcher

**Comment by NinjasInMyBasement** [comment]
Got it!
https://pastebin.com/xQ1286Y5
There is the log, copy and pasted as is

**Comment by covers1624** [comment]
That log mentions nothing of jei existing at all, make sure you have JEI: 1.4.3

**Comment by NinjasInMyBasement** [comment]
Hold on, I just found the issue. For some reason the curse forge website on the mod page the download link will download a version just before the current one. I went manually at the files and downloaded the most current. It is now working. Sorry for the inconvenience, but thank you for helping me!
