### ISSUE TITLE
had a crash when opening minecraft

### ISSUE THREAD

**Issue by Nisk24** [TheCBProject/NotEnoughItems#92]
After I installed the mod and tried to open minecraft I had a crash. I searched into the code that came up after the crash and I found out (exept that the game wanted to give me a teady bear so I wasn't angry) that NotEnoughItems was the mod that crashed me. Pls try and fix it I really want to play with this mod.

**Comment by covers1624** [comment]
What mc version? And please provide your crash report via http://pastebin.com

**Comment by Steven7597** [comment]
I believe I've had the same crash, my crash report can be found here: https://pastebin.com/mq5xsUxw

**Comment by covers1624** [comment]
@Steven7597 You have the Deobf version if NEI installed, install the universal version. As for OP. With out a crash report i can do nothing, closing.
