### ISSUE TITLE
Verbose log spamming (item filtering)

### ISSUE THREAD

**Issue by ACGaming** [TheCBProject/NotEnoughItems#93]
- Forge 1.10.2 12.18.3.2281
- CodeChickenCore 1.10.2 2.4.1.102
- CodeChickenLib 1.10.2 2.5.7.241
- NotEnoughItems 1.10.2 2.1.3.219
- JustEnoughItems 1.10.2 3.14.7.417

The newest version of NotEnoughItems seems to cause verbose log/console spamming related to item filtering or the like.

Here's an excerpt of my log: https://paste.ubuntu.com/24427086

EDIT: Did some further testing, problem does not occur with _NotEnoughItems 1.10.2 2.1.3.207_.

**Comment by Morpheus1101** [comment]
I Can confirm this occurs.  https://puu.sh/vsooN/9ed4a27b45.txt

Forge 1.10.2 12.18.3.2281
_CodeChickenCore 1.10.2 2.4.1.103_
_CodeChickenLib 1.10.2 2.5.7.255_
NotEnoughItems 1.10.2 2.1.3.219
JustEnoughItems 1.10.2 3.14.7.417

**Comment by KompuLogix** [comment]
I can also confirm this occurs. I was left with a log file over 1G in size within 2 hours of play time.
https://pastebin.com/bDggmvvT

forge-1.10.2-12.18.3.2281
CodeChickenCore 1.10.2 2.4.1.102
CodeChickenLib 1.10.2 2.5.7.241
NotEnoughItems 1.10.2 2.1.3.219
JustEnoughItems 1.10.2 3.14.7.417

**Comment by gigabit101** [comment]
@covers1624 is this going to be fixed any time soon?

**Comment by ACGaming** [comment]
We'll have to wait for covers1624 to come back, I believe.

**Comment by covers1624** [comment]
Ill have a fix out before the weekend.

**Comment by ACGaming** [comment]
I summoned him! 😯

**Comment by covers1624** [comment]
This has now been fixed, pushing build to curse.
