### ISSUE TITLE
Fluid Dumps aren't working (1.10.2)

### ISSUE THREAD

**Issue by BrisingrAerowing** [TheCBProject/NotEnoughItems#94]
I cannot get fluid dumps to work at all. All that happens is a 0 byte file is created. All other data dumps work as intended (and boy are they useful!).

MC 1.10.2
Forge 12.18.3.2281
NEI 2.1.3.219
JEI 3.14.7.417

[Mod list on Modlister](http://modlister.com/user/BrisingrAerowing)

**Comment by Vathoy** [comment]
Seconded, fluid and enchantment dumps are not working.
Stacktrace found here:
https://paste.ubuntu.com/24445321/

All other dumps appear to function correctly.
Hope this helps.

**Comment by BrisingrAerowing** [comment]
A quick check and I noticed the line that fails is the creation of the dump data. My guess is that there is a fluid that returns null for one of those methods, causing this error. Validating them beforehand would likely help.

**Comment by covers1624** [comment]
Fixed in 1.11
