### ISSUE TITLE
Issue #59 only fixed on 1.11 not 1.10

### ISSUE THREAD

**Issue by BeardlessBrady** [TheCBProject/NotEnoughItems#95]
As title states. 
https://github.com/TheCBProject/NotEnoughItems/issues/59

**Comment by covers1624** [comment]
You should be on 1.11 at this point, 1.10 i have no time to work on, large portions were rewritten in the 1.11 port and with 1.12 just around the corner i need to focus on that and finalizing 1.11.

**Comment by BeardlessBrady** [comment]
The issue was created months ago. But understandable
