### ISSUE TITLE
NEI still spamming console / logs in 1.10.2

### ISSUE THREAD

**Issue by Vaygrim** [TheCBProject/NotEnoughItems#96]
Issue #93 still hasn't been resolved with NEI under 1.10.2 , I'm still getting complaints from players even after updating to NEI 1.10.2-2.1.3.220-universal.

**Comment by Vaygrim** [comment]
Users are seeing the following (or very similar)... over and over.
`[NotEnoughItems]: Exception filtering null with codechicken.nei.ItemList$PatternItemFilter@42bdb8f2
java.lang.NullPointerException`

**Comment by Vaygrim** [comment]
Actually this time it appears to be linked to RAILCRAFT, hooray.
[Railraft #1178](https://github.com/CovertJaguar/Railcraft/pull/1178)

**Comment by darthvader45** [comment]
I'm having this issue without Railcraft.  Maybe it's also due to mods like Pam's Harvestcraft and Immersive Engineering.

**Comment by covers1624** [comment]
Mitigation has been implemented for 1.11, sadly with 1.12 arround the corner, i have no time to backport it to 1.10.
