### ISSUE TITLE
[1.10.2] Game crash after open inventory

### ISSUE THREAD

**Issue by bortooo** [TheCBProject/NotEnoughItems#97]
When I open inventory, the game crash. I try a few times in different worlds and always the same issue.
[Crash Report](https://pastebin.com/YWEA4ED5)

**Comment by covers1624** [comment]
Has this ever occurred again?, i cant see why this would happen in the first place..

**Comment by bortooo** [comment]
I was playing a custom modpack in a survival world but I stopped playing when the bug appeared. I reported the bug, hoping it was fixed in a few day, but after two week I changed modpack and the bug hasn't happend yet.
