### ISSUE TITLE
Crash Report at start up (MC 1.11.2)

### ISSUE THREAD

**Issue by stranger195** [TheCBProject/NotEnoughItems#98]
I click "Play" on the Minecraft Launcher. Mojang logo appears with Forge logo at the bottom-right, with "Memory Used" bar at the top and two bars saying that Forge is loading mods at the bottom of the logo. And then crash.

https://pastebin.com/MUC1GCcs

**Comment by covers1624** [comment]
You are using an un released version that has impropper dependencies hence why its un released. Update your CCL and NEI.
