### ISSUE TITLE
Highlight tips Option

### ISSUE THREAD

**Issue by CreedOX** [TheCBProject/NotEnoughItems#99]
Hey Guys - so s.th. which is not really an issue but drives me crazy  is that i cant find the Highlight tips option in the "Options" section? So is it planned to be implemented in 1.11.2 or am i just very blind?

Hope u can help me with that - cheers

**Comment by covers1624** [comment]
Not sure what you mean. Can you provide some more info as to what issue you are experiencing please? maybe some screenshots.

**Comment by covers1624** [comment]
Closing outdated, no response for information.
